# **Dataset Structure Exploration**

In [1]:
import sys
print(sys.executable)

C:\Users\dell\anaconda3\envs\mtcnn_env\python.exe

In [ ]:
!pip install facenet-pytorch

In [2]:
import os
os.path.getsize("mind_w.zip")

14495514624

In [ ]:
!pip install py7zr

## Ensuring correct folder

In [3]:
import os

dataset_path = "mind_w"

for class_name in os.listdir(dataset_path):
    class_path = os.path.join(dataset_path,class_name)
    if os.path.isdir(class_path):
        print(f"class: {class_name}, files: {len(os.listdir(class_path))}")

class: Labels, files: 3
class: Test, files: 21
class: Train, files: 70
class: Validation, files: 20

## Want to ensure that how many classes "Train" have stored

In [8]:
Train_dataset_path = "mind_w/Train"

for class_name in os.listdir(Train_dataset_path):
    class_path = os.path.join(Train_dataset_path, class_name)
    if os.path.isdir(class_path):
        print(f"class: {class_name}, video: {len(os.listdir(class_path))}")

class: 110001, video: 114
class: 110002, video: 41
class: 110004, video: 34
class: 110005, video: 93
class: 110006, video: 79
class: 110007, video: 142
class: 110008, video: 9
class: 110010, video: 1
class: 110011, video: 75
class: 110012, video: 87
class: 110013, video: 8
class: 110014, video: 89
class: 110015, video: 78
class: 110016, video: 31
class: 110017, video: 78
class: 110041, video: 29
class: 111003, video: 68
class: 181374, video: 112
class: 200048, video: 31
class: 200049, video: 14
class: 200050, video: 109
class: 200054, video: 89
class: 202614, video: 77
class: 205601, video: 88
class: 210051, video: 90
class: 210052, video: 111
class: 210053, video: 127
class: 210055, video: 121
class: 210056, video: 85
class: 210057, video: 118
class: 210058, video: 99
class: 210059, video: 124
class: 210060, video: 121
class: 210061, video: 123
class: 226051, video: 95
class: 240846, video: 89
class: 248510, video: 80
class: 290428, video: 93
class: 303830, video: 83
class: 310062, video: 86
class: 310063, video: 70
class: 310064, video: 53
class: 310066, video: 45
class: 310068, video: 19
class: 310069, video: 38
class: 310070, video: 83
class: 310071, video: 9
class: 310072, video: 113
class: 310073, video: 46
class: 310074, video: 107
class: 310075, video: 109
class: 310076, video: 43
class: 310077, video: 114
class: 310078, video: 116
class: 310079, video: 87
class: 310080, video: 3
class: 310081, video: 46
class: 310082, video: 55
class: 310083, video: 29
class: 334463, video: 108
class: 337021, video: 90
class: 342227, video: 97
class: 350361, video: 113
class: 400018, video: 118
class: 401835, video: 83
class: 411021, video: 112
class: 411031, video: 53
class: 414081, video: 111
class: 459999, video: 82
class: 522129, video: 109

In [4]:
os.listdir("mind_w")

['Labels', 'Test', 'Train', 'Validation']

In [5]:
os.listdir("mind_w/Labels")

['TestLabels.csv', 'TrainLabels.csv', 'ValidationLabels.csv']

In [4]:
#Verifying Installed Library Versions
import numpy as np
import pandas as pd
import cv2
import torch

print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)
print("OpenCV:", cv2.__version__)
print("Torch:", torch.__version__)

NumPy: 1.26.4
Pandas: 2.3.3
OpenCV: 4.7.0
Torch: 2.2.2+cpu

## Scanning & Collecting all video files.

In [5]:
root_folder = r"C:\Users\dell\mind_w\Train"

#List to store all video files
video_files = []
# Walk through all subfolders
for subdir,dirs,files in os.walk(root_folder):
    for f in files:
        if f.lower().endswith(('.avi', '.AVI', '.mov', '.mpg', '.mp4')):
            full_path = os.path.join(subdir,f)
            video_files.append(full_path)

print("Total Video Found: ", len(video_files))
# show first 10 videos as a sample
print(video_files[:10])

Total Video Found:  10456
['C:\\Users\\dell\\mind_w\\Train\\110001\\1100011002\\1100011002.avi', 'C:\\Users\\dell\\mind_w\\Train\\110001\\1100011002\\1100011002.mp4', 'C:\\Users\\dell\\mind_w\\Train\\110001\\1100011003\\1100011003.avi', 'C:\\Users\\dell\\mind_w\\Train\\110001\\1100011003\\1100011003.mp4', 'C:\\Users\\dell\\mind_w\\Train\\110001\\1100011004\\1100011004.avi', 'C:\\Users\\dell\\mind_w\\Train\\110001\\1100011004\\1100011004.mp4', 'C:\\Users\\dell\\mind_w\\Train\\110001\\1100011005\\1100011005.avi', 'C:\\Users\\dell\\mind_w\\Train\\110001\\1100011005\\1100011005.mp4', 'C:\\Users\\dell\\mind_w\\Train\\110001\\1100011006\\1100011006.avi', 'C:\\Users\\dell\\mind_w\\Train\\110001\\1100011006\\1100011006.mp4']

## Convert all videos to .mp4

In [9]:
import subprocess

PRINT_LIMIT = 10   # only show logs for first 10 files

for idx, file_path in enumerate(video_files):
    # Skip if already .mp4
    if file_path.lower().endswith('.mp4'):
        continue

    # Output path: same folder, same name with .mp4 extension
    output_path = os.path.splitext(file_path)[0] + ".mp4"

    # FFmpeg command
    command = [
        "ffmpeg",
        "-i", file_path,
        "-c:v", "libx264",
        "-preset", "fast",
        "-crf", "23",
        "-c:a", "aac",
        output_path
    ]

    subprocess.run(
        command,
        stdout=subprocess.DEVNULL,   # silence ffmpeg output
        stderr=subprocess.DEVNULL
    )
    if idx < PRINT_LIMIT:
        print(f"Converted: {file_path} → {output_path}")

Converted: C:\Users\dell\mind_w\Train\110001\1100011002\1100011002.avi → C:\Users\dell\mind_w\Train\110001\1100011002\1100011002.mp4
Converted: C:\Users\dell\mind_w\Train\110001\1100011003\1100011003.avi → C:\Users\dell\mind_w\Train\110001\1100011003\1100011003.mp4
Converted: C:\Users\dell\mind_w\Train\110001\1100011004\1100011004.avi → C:\Users\dell\mind_w\Train\110001\1100011004\1100011004.mp4
Converted: C:\Users\dell\mind_w\Train\110001\1100011005\1100011005.avi → C:\Users\dell\mind_w\Train\110001\1100011005\1100011005.mp4
Converted: C:\Users\dell\mind_w\Train\110001\1100011006\1100011006.avi → C:\Users\dell\mind_w\Train\110001\1100011006\1100011006.mp4

# **Video Frame Extraction and Preprocessing**

In [14]:
!pip install opencv-python-headless

Requirement already satisfied: opencv-python-headless in c:\users\dell\anaconda3\lib\site-packages (4.12.0)

# Time based sampling

In [6]:
def load_video(video_path, num_frames=24):
    frames = []

    try:
        cap = cv2.VideoCapture(video_path)
        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        fps = cap.get(cv2.CAP_PROP_FPS)

        if total_frames == 0 or fps == 0:
            return None

        # sample one frame every 0.5 seconds
        step = int(fps * 0.5)

        for i in range(0, total_frames, step):
            cap.set(cv2.CAP_PROP_POS_FRAMES, i)
            ret, frame = cap.read()
            if not ret:
                continue

            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            frame = cv2.resize(frame, (224, 224))
            frames.append(frame)

            if len(frames) == num_frames:
                break

        cap.release()
        return np.array(frames)

    except Exception as e:
        print(f"Error reading {video_path}: {e}")
        return None

In [9]:
for root, dirs, files in os.walk(Train_dataset_path):
    for file in files:
        if file.lower().endswith(".mp4"):
            print(os.path.join(root,file))

mind_w/Train\110001\1100011002\1100011002.mp4
mind_w/Train\110001\1100011003\1100011003.mp4
mind_w/Train\110001\1100011004\1100011004.mp4
mind_w/Train\110001\1100011005\1100011005.mp4
mind_w/Train\110001\1100011006\1100011006.mp4
mind_w/Train\110001\1100011007\1100011007.mp4
mind_w/Train\110001\1100011008\1100011008.mp4
mind_w/Train\110001\1100011009\1100011009.mp4
mind_w/Train\110001\1100011010\1100011010.mp4
mind_w/Train\110001\1100011011\1100011011.mp4
mind_w/Train\110001\1100011012\1100011012.mp4
mind_w/Train\110001\1100011013\1100011013.mp4
mind_w/Train\110001\1100011014\1100011014.mp4
mind_w/Train\110001\1100011015\1100011015.mp4
mind_w/Train\110001\1100011016\1100011016.mp4
mind_w/Train\110001\1100011017\1100011017.mp4
mind_w/Train\110001\1100011018\1100011018.mp4
mind_w/Train\110001\1100011019\1100011019.mp4
mind_w/Train\110001\1100011020\1100011020.mp4
mind_w/Train\110001\1100011021\1100011021.mp4
mind_w/Train\110001\1100011022\1100011022.mp4
mind_w/Train\110001\1100011023\1100011023.mp4
mind_w/Train\110001\1100011025\1100011025.mp4
mind_w/Train\110001\1100011026\1100011026.mp4
mind_w/Train\110001\1100011027\1100011027.mp4
mind_w/Train\110001\1100011028\1100011028.mp4
mind_w/Train\110001\1100011029\1100011029.mp4
mind_w/Train\110001\1100011031\1100011031.mp4
mind_w/Train\110001\1100011032\1100011032.mp4
mind_w/Train\110001\1100011034\1100011034.mp4
mind_w/Train\110001\1100011035\1100011035.mp4
mind_w/Train\110001\1100011037\1100011037.mp4
mind_w/Train\110001\1100011038\1100011038.mp4
mind_w/Train\110001\1100011040\1100011040.mp4
mind_w/Train\110001\1100011046\1100011046.mp4
mind_w/Train\110001\1100011047\1100011047.mp4
mind_w/Train\110001\1100011048\1100011048.mp4
mind_w/Train\110001\1100011049\1100011049.mp4
mind_w/Train\110001\1100011050\1100011050.mp4
mind_w/Train\110001\1100011051\1100011051.mp4
mind_w/Train\110001\1100011052\1100011052.mp4
mind_w/Train\110001\1100011053\1100011053.mp4
mind_w/Train\110001\1100011054\1100011054.mp4
mind_w/Train\110001\1100011055\1100011055.mp4
mind_w/Train\110001\1100011056\1100011056.mp4
mind_w/Train\110001\1100011057\1100011057.mp4
mind_w/Train\110001\1100011058\1100011058.mp4
mind_w/Train\110001\1100011059\1100011059.mp4
mind_w/Train\110001\1100011060\1100011060.mp4
mind_w/Train\110001\1100011062\1100011062.mp4
mind_w/Train\110001\1100011063\1100011063.mp4
mind_w/Train\110001\1100011064\1100011064.mp4
mind_w/Train\110001\1100011066\1100011066.mp4
mind_w/Train\110001\1100011067\1100011067.mp4
mind_w/Train\110001\1100011068\1100011068.mp4
mind_w/Train\110001\1100011069\1100011069.mp4
mind_w/Train\110001\1100011070\1100011070.mp4
mind_w/Train\110001\1100011071\1100011071.mp4
mind_w/Train\110001\1100011072\1100011072.mp4
mind_w/Train\110001\1100011073\1100011073.mp4
mind_w/Train\110001\1100011075\1100011075.mp4
mind_w/Train\110001\1100011076\1100011076.mp4
mind_w/Train\110001\1100011078\1100011078.mp4
mind_w/Train\110001\1100011079\1100011079.mp4
mind_w/Train\110001\1100011080\1100011080.mp4
mind_w/Train\110001\1100011081\1100011081.mp4
mind_w/Train\110001\1100011082\1100011082.mp4
mind_w/Train\110001\1100011083\1100011083.mp4
mind_w/Train\110001\1100012001\1100012001.mp4
mind_w/Train\110001\1100012003\1100012003.mp4
mind_w/Train\110001\1100012007\1100012007.mp4
mind_w/Train\110001\1100012008\1100012008.mp4
mind_w/Train\110001\1100012009\1100012009.mp4
mind_w/Train\110001\1100012010\1100012010.mp4
mind_w/Train\110001\1100012011\1100012011.mp4
mind_w/Train\110001\1100012013\1100012013.mp4
mind_w/Train\110001\1100012014\1100012014.mp4
mind_w/Train\110001\1100012015\1100012015.mp4
mind_w/Train\110001\1100012016\1100012016.mp4
mind_w/Train\110001\1100012017\1100012017.mp4
mind_w/Train\110001\1100012018\1100012018.mp4
mind_w/Train\110001\1100012021\1100012021.mp4
mind_w/Train\110001\1100012022\1100012022.mp4
mind_w/Train\110001\1100012023\1100012023.mp4
mind_w/Train\110001\1100012025\1100012025.mp4
mind_w/Train\110001\1100012026\1100012026.mp4
mind_w/Train\110001\1100012027\1100012027.mp4
mind_w/Train\110001\1100012028\1100012028.mp4
mind_w/Train\110001\1100012030\1100012030.mp4
mind_w/Train\110001\1100012031\1100012031.mp4
mind_w/Train\110001\1100012032\1100012032.mp4
mind_w/Train\110001\1100012033\1100012033.mp4
mind_w/Train\110001\1100012036\1100012036.mp4
mind_w/Train\110001\1100012037\1100012037.mp4
mind_w/Train\110001\1100012038\1100012038.mp4
mind_w/Train\110001\1100012041\1100012041.mp4
mind_w/Train\110001\1100012042\1100012042.mp4
mind_w/Train\110001\1100012045\1100012045.mp4
mind_w/Train\110001\1100012046\1100012046.mp4
mind_w/Train\110001\1100012047\1100012047.mp4
mind_w/Train\110001\1100012049\1100012049.mp4
mind_w/Train\110001\1100012050\1100012050.mp4
mind_w/Train\110001\1100012051\1100012051.mp4
mind_w/Train\110001\1100012052\1100012052.mp4
mind_w/Train\110001\1100012057\1100012057.mp4
mind_w/Train\110001\1100012059\1100012059.mp4
mind_w/Train\110001\1100012060\1100012060.mp4
mind_w/Train\110001\1100012061\1100012061.mp4
mind_w/Train\110001\1100012062\1100012062.mp4
mind_w/Train\110001\1100012063\1100012063.mp4
mind_w/Train\110001\1100012064\1100012064.mp4
mind_w/Train\110001\1100012065\1100012065.mp4
mind_w/Train\110001\1100012066\1100012066.mp4
mind_w/Train\110001\1100012069\1100012069.mp4
mind_w/Train\110002\1100021001\1100021001.mp4
mind_w/Train\110002\1100021003\1100021003.mp4
mind_w/Train\110002\1100021015\1100021015.mp4
mind_w/Train\110002\1100021038\1100021038.mp4
mind_w/Train\110002\1100021039\1100021039.mp4
mind_w/Train\110002\1100021040\1100021040.mp4
mind_w/Train\110002\1100021045\1100021045.mp4
mind_w/Train\110002\1100021050\1100021050.mp4
mind_w/Train\110002\1100021055\1100021055.mp4
mind_w/Train\110002\1100022001\1100022001.mp4
mind_w/Train\110002\1100022002\1100022002.mp4
mind_w/Train\110002\1100022003\1100022003.mp4
mind_w/Train\110002\1100022004\1100022004.mp4
mind_w/Train\110002\1100022005\1100022005.mp4
mind_w/Train\110002\1100022008\1100022008.mp4
mind_w/Train\110002\1100022009\1100022009.mp4
mind_w/Train\110002\1100022014\1100022014.mp4
mind_w/Train\110002\1100022019\1100022019.mp4
mind_w/Train\110002\1100022020\1100022020.mp4
mind_w/Train\110002\1100022021\1100022021.mp4
mind_w/Train\110002\1100022022\1100022022.mp4
mind_w/Train\110002\1100022026\1100022026.mp4
mind_w/Train\110002\1100022027\1100022027.mp4
mind_w/Train\110002\1100022028\1100022028.mp4
mind_w/Train\110002\1100022029\1100022029.mp4
mind_w/Train\110002\1100022031\1100022031.mp4
mind_w/Train\110002\1100022035\1100022035.mp4
mind_w/Train\110002\1100022038\1100022038.mp4
mind_w/Train\110002\1100022039\1100022039.mp4
mind_w/Train\110002\1100022045\1100022045.mp4
mind_w/Train\110002\1100022046\1100022046.mp4
mind_w/Train\110002\1100022047\1100022047.mp4
mind_w/Train\110002\1100022048\1100022048.mp4
mind_w/Train\110002\1100022049\1100022049.mp4
mind_w/Train\110002\1100022051\1100022051.mp4
mind_w/Train\110002\1100022052\1100022052.mp4
mind_w/Train\110002\1100022053\1100022053.mp4
mind_w/Train\110002\1100022054\1100022054.mp4
mind_w/Train\110002\1100022055\1100022055.mp4
mind_w/Train\110002\1100022056\1100022056.mp4
mind_w/Train\110002\1100022057\1100022057.mp4
mind_w/Train\110004\1100041006\1100041006.mp4
mind_w/Train\110004\1100041015\1100041015.mp4
mind_w/Train\110004\1100041016\1100041016.mp4
mind_w/Train\110004\1100041017\1100041017.mp4
mind_w/Train\110004\1100041018\1100041018.mp4
mind_w/Train\110004\1100041021\1100041021.mp4
mind_w/Train\110004\1100041022\1100041022.mp4
mind_w/Train\110004\1100041023\1100041023.mp4
mind_w/Train\110004\1100041024\1100041024.mp4
mind_w/Train\110004\1100041029\1100041029.mp4
mind_w/Train\110004\1100041034\1100041034.mp4
mind_w/Train\110004\1100041044\1100041044.mp4
mind_w/Train\110004\1100041051\1100041051.mp4
mind_w/Train\110004\1100041052\1100041052.mp4
mind_w/Train\110004\1100042009\1100042009.mp4
mind_w/Train\110004\1100042010\1100042010.mp4
mind_w/Train\110004\1100042011\1100042011.mp4
mind_w/Train\110004\1100042017\1100042017.mp4
mind_w/Train\110004\1100042018\1100042018.mp4
mind_w/Train\110004\1100042019\1100042019.mp4
mind_w/Train\110004\1100042020\1100042020.mp4
mind_w/Train\110004\1100042023\1100042023.mp4
mind_w/Train\110004\1100042024\1100042024.mp4
mind_w/Train\110004\1100042025\1100042025.mp4
mind_w/Train\110004\1100042026\1100042026.mp4
mind_w/Train\110004\1100042029\1100042029.mp4
mind_w/Train\110004\1100042030\1100042030.mp4
mind_w/Train\110004\1100042031\1100042031.mp4
mind_w/Train\110004\1100042034\1100042034.mp4
mind_w/Train\110004\1100042040\1100042040.mp4
mind_w/Train\110004\1100042041\1100042041.mp4
mind_w/Train\110004\1100042058\1100042058.mp4
mind_w/Train\110004\1100042059\1100042059.mp4
mind_w/Train\110004\1100042060\1100042060.mp4
mind_w/Train\110005\1100051002\1100051002.mp4
mind_w/Train\110005\1100051004\1100051004.mp4
mind_w/Train\110005\1100051006\1100051006.mp4
mind_w/Train\110005\1100051007\1100051007.mp4
mind_w/Train\110005\1100051008\1100051008.mp4
mind_w/Train\110005\1100051009\1100051009.mp4
mind_w/Train\110005\1100051011\1100051011.mp4
mind_w/Train\110005\1100051012\1100051012.mp4
mind_w/Train\110005\1100051013\1100051013.mp4
mind_w/Train\110005\1100051014\1100051014.mp4
mind_w/Train\110005\1100051016\1100051016.mp4
mind_w/Train\110005\1100051017\1100051017.mp4
mind_w/Train\110005\1100051019\1100051019.mp4
mind_w/Train\110005\1100051020\1100051020.mp4
mind_w/Train\110005\1100051021\1100051021.mp4
mind_w/Train\110005\1100051022\1100051022.mp4
mind_w/Train\110005\1100051023\1100051023.mp4
mind_w/Train\110005\1100051024\1100051024.mp4
mind_w/Train\110005\1100051025\1100051025.mp4
mind_w/Train\110005\1100051026\1100051026.mp4
mind_w/Train\110005\1100051028\1100051028.mp4
mind_w/Train\110005\1100051029\1100051029.mp4
mind_w/Train\110005\1100051030\1100051030.mp4
mind_w/Train\110005\1100051031\1100051031.mp4
mind_w/Train\110005\1100051032\1100051032.mp4
mind_w/Train\110005\1100051033\1100051033.mp4
mind_w/Train\110005\1100051034\1100051034.mp4
mind_w/Train\110005\1100051035\1100051035.mp4
mind_w/Train\110005\1100051036\1100051036.mp4
mind_w/Train\110005\1100051037\1100051037.mp4
mind_w/Train\110005\1100051039\1100051039.mp4
mind_w/Train\110005\1100051041\1100051041.mp4
mind_w/Train\110005\1100051042\1100051042.mp4
mind_w/Train\110005\1100051044\1100051044.mp4
mind_w/Train\110005\1100051045\1100051045.mp4
mind_w/Train\110005\1100051046\1100051046.mp4
mind_w/Train\110005\1100051048\1100051048.mp4
mind_w/Train\110005\1100051049\1100051049.mp4
mind_w/Train\110005\1100051050\1100051050.mp4
mind_w/Train\110005\1100051051\1100051051.mp4
mind_w/Train\110005\1100051052\1100051052.mp4
mind_w/Train\110005\1100051053\1100051053.mp4
mind_w/Train\110005\1100051054\1100051054.mp4
mind_w/Train\110005\1100051055\1100051055.mp4
mind_w/Train\110005\1100051056\1100051056.mp4
mind_w/Train\110005\1100051057\1100051057.mp4
mind_w/Train\110005\1100051059\1100051059.mp4
mind_w/Train\110005\1100051061\1100051061.mp4
mind_w/Train\110005\1100051062\1100051062.mp4
mind_w/Train\110005\1100051064\1100051064.mp4
mind_w/Train\110005\1100051065\1100051065.mp4
mind_w/Train\110005\1100051066\1100051066.mp4
mind_w/Train\110005\1100051067\1100051067.mp4
mind_w/Train\110005\1100051068\1100051068.mp4
mind_w/Train\110005\1100051071\1100051071.mp4
mind_w/Train\110005\1100051076\1100051076.mp4
mind_w/Train\110005\1100051078\1100051078.mp4
mind_w/Train\110005\1100051079\1100051079.mp4
mind_w/Train\110005\1100052001\1100052001.mp4
mind_w/Train\110005\1100052002\1100052002.mp4
mind_w/Train\110005\1100052006\1100052006.mp4
mind_w/Train\110005\1100052007\1100052007.mp4
mind_w/Train\110005\1100052008\1100052008.mp4
mind_w/Train\110005\1100052009\1100052009.mp4
mind_w/Train\110005\1100052014\1100052014.mp4
mind_w/Train\110005\1100052023\1100052023.mp4
mind_w/Train\110005\1100052024\1100052024.mp4
mind_w/Train\110005\1100052026\1100052026.mp4
mind_w/Train\110005\1100052027\1100052027.mp4
mind_w/Train\110005\1100052028\1100052028.mp4
mind_w/Train\110005\1100052030\1100052030.mp4
mind_w/Train\110005\1100052031\1100052031.mp4
mind_w/Train\110005\1100052032\1100052032.mp4
mind_w/Train\110005\1100052033\1100052033.mp4
mind_w/Train\110005\1100052035\1100052035.mp4
mind_w/Train\110005\1100052036\1100052036.mp4
mind_w/Train\110005\1100052037\1100052037.mp4
mind_w/Train\110005\1100052038\1100052038.mp4
mind_w/Train\110005\1100052039\1100052039.mp4
mind_w/Train\110005\1100052040\1100052040.mp4
mind_w/Train\110005\1100052041\1100052041.mp4
mind_w/Train\110005\1100052047\1100052047.mp4
mind_w/Train\110005\1100052048\1100052048.mp4
mind_w/Train\110005\1100052049\1100052049.mp4
mind_w/Train\110005\1100052051\1100052051.mp4
mind_w/Train\110005\1100052055\1100052055.mp4
mind_w/Train\110005\1100052057\1100052057.mp4
mind_w/Train\110005\1100052060\1100052060.mp4
mind_w/Train\110005\1100052061\1100052061.mp4
mind_w/Train\110005\1100052062\1100052062.mp4
mind_w/Train\110005\1100052065\1100052065.mp4
mind_w/Train\110005\1100052068\1100052068.mp4
mind_w/Train\110005\1100052070\1100052070.mp4
mind_w/Train\110006\1100061009\1100061009.mp4
mind_w/Train\110006\1100061010\1100061010.mp4
mind_w/Train\110006\1100061011\1100061011.mp4
mind_w/Train\110006\1100061012\1100061012.mp4
mind_w/Train\110006\1100061013\1100061013.mp4
mind_w/Train\110006\1100061015\1100061015.mp4
mind_w/Train\110006\1100061016\1100061016.mp4
mind_w/Train\110006\1100061018\1100061018.mp4
mind_w/Train\110006\1100061019\1100061019.mp4
mind_w/Train\110006\1100061022\1100061022.mp4
mind_w/Train\110006\1100061023\1100061023.mp4
mind_w/Train\110006\1100061025\1100061025.mp4
mind_w/Train\110006\1100061027\1100061027.mp4
mind_w/Train\110006\1100061028\1100061028.mp4
mind_w/Train\110006\1100061030\1100061030.mp4
mind_w/Train\110006\1100061031\1100061031.mp4
mind_w/Train\110006\1100061032\1100061032.mp4
mind_w/Train\110006\1100061033\1100061033.mp4
mind_w/Train\110006\1100061034\1100061034.mp4
mind_w/Train\110006\1100061035\1100061035.mp4
mind_w/Train\110006\1100061036\1100061036.mp4
mind_w/Train\110006\1100061038\1100061038.mp4
mind_w/Train\110006\1100061039\1100061039.mp4
mind_w/Train\110006\1100061040\1100061040.mp4
mind_w/Train\110006\1100061042\1100061042.mp4
mind_w/Train\110006\1100061043\1100061043.mp4
mind_w/Train\110006\1100061044\1100061044.mp4
mind_w/Train\110006\1100061046\1100061046.mp4
mind_w/Train\110006\1100061047\1100061047.mp4
mind_w/Train\110006\1100061048\1100061048.mp4
mind_w/Train\110006\1100061049\1100061049.mp4
mind_w/Train\110006\1100061050\1100061050.mp4
mind_w/Train\110006\1100061051\1100061051.mp4
mind_w/Train\110006\1100061053\1100061053.mp4
mind_w/Train\110006\1100061057\1100061057.mp4
mind_w/Train\110006\1100061058\1100061058.mp4
mind_w/Train\110006\1100061061\1100061061.mp4
mind_w/Train\110006\1100061063\1100061063.mp4
mind_w/Train\110006\1100061064\1100061064.mp4
mind_w/Train\110006\1100061067\1100061067.mp4
mind_w/Train\110006\1100061068\1100061068.mp4
mind_w/Train\110006\1100061069\1100061069.mp4
mind_w/Train\110006\1100061073\1100061073.mp4
mind_w/Train\110006\1100061074\1100061074.mp4
mind_w/Train\110006\1100061077\1100061077.mp4
mind_w/Train\110006\1100061078\1100061078.mp4
mind_w/Train\110006\1100062004\1100062004.mp4
mind_w/Train\110006\1100062005\1100062005.mp4
mind_w/Train\110006\1100062007\1100062007.mp4
mind_w/Train\110006\1100062008\1100062008.mp4
mind_w/Train\110006\1100062009\1100062009.mp4
mind_w/Train\110006\1100062016\1100062016.mp4
mind_w/Train\110006\1100062017\1100062017.mp4
mind_w/Train\110006\1100062024\1100062024.mp4
mind_w/Train\110006\1100062028\1100062028.mp4
mind_w/Train\110006\1100062029\1100062029.mp4
mind_w/Train\110006\1100062036\1100062036.mp4
mind_w/Train\110006\1100062037\1100062037.mp4
mind_w/Train\110006\1100062044\1100062044.mp4
mind_w/Train\110006\1100062045\1100062045.mp4
mind_w/Train\110006\1100062046\1100062046.mp4
mind_w/Train\110006\1100062049\1100062049.mp4
mind_w/Train\110006\1100062051\1100062051.mp4
mind_w/Train\110006\1100062053\1100062053.mp4
mind_w/Train\110006\1100062054\1100062054.mp4
mind_w/Train\110006\1100062059\1100062059.mp4
mind_w/Train\110006\1100062060\1100062060.mp4
mind_w/Train\110006\1100062061\1100062061.mp4
mind_w/Train\110006\1100062062\1100062062.mp4
mind_w/Train\110006\1100062063\1100062063.mp4
mind_w/Train\110006\1100062064\1100062064.mp4
mind_w/Train\110006\1100062065\1100062065.mp4
mind_w/Train\110006\1100062066\1100062066.mp4
mind_w/Train\110006\1100062067\1100062067.mp4
mind_w/Train\110006\1100062068\1100062068.mp4
mind_w/Train\110006\1100062069\1100062069.mp4
mind_w/Train\110006\1100062070\1100062070.mp4
mind_w/Train\110006\1100062071\1100062071.mp4
mind_w/Train\110006\1100062072\1100062072.mp4
mind_w/Train\110007\1100071005\1100071005.mp4
mind_w/Train\110007\1100071006\1100071006.mp4
mind_w/Train\110007\1100071007\1100071007.mp4
mind_w/Train\110007\1100071008\1100071008.mp4
mind_w/Train\110007\1100071009\1100071009.mp4
mind_w/Train\110007\1100071010\1100071010.mp4
mind_w/Train\110007\1100071011\1100071011.mp4
mind_w/Train\110007\1100071012\1100071012.mp4
mind_w/Train\110007\1100071013\1100071013.mp4
mind_w/Train\110007\1100071014\1100071014.mp4
mind_w/Train\110007\1100071015\1100071015.mp4
mind_w/Train\110007\1100071016\1100071016.mp4
mind_w/Train\110007\1100071017\1100071017.mp4
mind_w/Train\110007\1100071018\1100071018.mp4
mind_w/Train\110007\1100071019\1100071019.mp4
mind_w/Train\110007\1100071020\1100071020.mp4
mind_w/Train\110007\1100071021\1100071021.mp4
mind_w/Train\110007\1100071022\1100071022.mp4
mind_w/Train\110007\1100071023\1100071023.mp4
mind_w/Train\110007\1100071024\1100071024.mp4
mind_w/Train\110007\1100071026\1100071026.mp4
mind_w/Train\110007\1100071027\1100071027.mp4
mind_w/Train\110007\1100071028\1100071028.mp4
mind_w/Train\110007\1100071029\1100071029.mp4
mind_w/Train\110007\1100071030\1100071030.mp4
mind_w/Train\110007\1100071031\1100071031.mp4
mind_w/Train\110007\1100071032\1100071032.mp4
mind_w/Train\110007\1100071033\1100071033.mp4
mind_w/Train\110007\1100071034\1100071034.mp4
mind_w/Train\110007\1100071035\1100071035.mp4
mind_w/Train\110007\1100071036\1100071036.mp4
mind_w/Train\110007\1100071037\1100071037.mp4
mind_w/Train\110007\1100071040\1100071040.mp4
mind_w/Train\110007\1100071041\1100071041.mp4
mind_w/Train\110007\1100071042\1100071042.mp4
mind_w/Train\110007\1100071043\1100071043.mp4
mind_w/Train\110007\1100071044\1100071044.mp4
mind_w/Train\110007\1100071045\1100071045.mp4
mind_w/Train\110007\1100071046\1100071046.mp4
mind_w/Train\110007\1100071047\1100071047.mp4
mind_w/Train\110007\1100071049\1100071049.mp4
mind_w/Train\110007\1100071050\1100071050.mp4
mind_w/Train\110007\1100071052\1100071052.mp4
mind_w/Train\110007\1100071054\1100071054.mp4
mind_w/Train\110007\1100071055\1100071055.mp4
mind_w/Train\110007\1100071056\1100071056.mp4
mind_w/Train\110007\1100071057\1100071057.mp4
mind_w/Train\110007\1100071058\1100071058.mp4
mind_w/Train\110007\1100071059\1100071059.mp4
mind_w/Train\110007\1100071060\1100071060.mp4
mind_w/Train\110007\1100071061\1100071061.mp4
mind_w/Train\110007\1100071062\1100071062.mp4
mind_w/Train\110007\1100071063\1100071063.mp4
mind_w/Train\110007\1100071064\1100071064.mp4
mind_w/Train\110007\1100071065\1100071065.mp4
mind_w/Train\110007\1100071066\1100071066.mp4
mind_w/Train\110007\1100071067\1100071067.mp4
mind_w/Train\110007\1100071069\1100071069.mp4
mind_w/Train\110007\1100071070\1100071070.mp4
mind_w/Train\110007\1100071071\1100071071.mp4
mind_w/Train\110007\1100071072\1100071072.mp4
mind_w/Train\110007\1100071073\1100071073.mp4
mind_w/Train\110007\1100071074\1100071074.mp4
mind_w/Train\110007\1100071075\1100071075.mp4
mind_w/Train\110007\1100071076\1100071076.mp4
mind_w/Train\110007\1100071077\1100071077.mp4
mind_w/Train\110007\1100071078\1100071078.mp4
mind_w/Train\110007\1100071079\1100071079.mp4
mind_w/Train\110007\1100071080\1100071080.mp4
mind_w/Train\110007\1100071081\1100071081.mp4
mind_w/Train\110007\1100072001\1100072001.mp4
mind_w/Train\110007\1100072002\1100072002.mp4
mind_w/Train\110007\1100072003\1100072003.mp4

In [10]:
frames = load_video("mind_w/Train/110001/1100011016/1100011016.mp4",24)

In [11]:
# visualize one frame:
cv2.imshow("Face Image", frames[0])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
print(type(frames))
print(frames.shape)

<class 'numpy.ndarray'>
(20, 224, 224, 3)

In [13]:
cap = cv2.VideoCapture("mind_w/Train/110001/1100011018/1100011018.mp4")
print("Is video opened?:", cap.isOpened())
print("Total frames:", int(cap.get(cv2.CAP_PROP_FRAME_COUNT)))
print("FPS:", cap.get(cv2.CAP_PROP_FPS))

Is video opened?: True
Total frames: 300
FPS: 30.0

In [14]:
print(os.listdir("mind_w/Train"))

['110001', '110002', '110004', '110005', '110006', '110007', '110008', '110010', '110011', '110012', '110013', '110014', '110015', '110016', '110017', '110041', '111003', '181374', '200048', '200049', '200050', '200054', '202614', '205601', '210051', '210052', '210053', '210055', '210056', '210057', '210058', '210059', '210060', '210061', '226051', '240846', '248510', '290428', '303830', '310062', '310063', '310064', '310066', '310068', '310069', '310070', '310071', '310072', '310073', '310074', '310075', '310076', '310077', '310078', '310079', '310080', '310081', '310082', '310083', '334463', '337021', '342227', '350361', '400018', '401835', '411021', '411031', '414081', '459999', '522129']

In [15]:
print("frame dtype:", frames.dtype)
print("single frame shape:", frames[0].shape)

frame dtype: uint8
single frame shape: (224, 224, 3)

In [16]:
#Clear unused memory
import gc
gc.collect()
#del frames

480

In [17]:
#Limit the frame
frames = frames[:15]

In [15]:
# visualization of one frame as image
cv2.imshow("Frame 0", frames[14])   # OpenCV expects BGR
cv2.waitKey(0)
cv2.destroyAllWindows()

# Convert to grayscale before difference

## Reduces noise

In [18]:
# Compare frame 0 and frame 4
frame1 = frames[0]
frame2 = frames[1]
gray1 = cv2.cvtColor(frame1, cv2.COLOR_BGR2GRAY)
gray2 = cv2.cvtColor(frame2, cv2.COLOR_BGR2GRAY)
mean_diff = np.mean(np.abs(gray1 - gray2))
print("Mean pixel difference:",mean_diff)

Mean pixel difference: 73.26911272321429

# Step-2 : MTCNN Face Detection

In [19]:
from facenet_pytorch import MTCNN
import cv2
import numpy as np

C:\Users\dell\anaconda3\envs\mtcnn_env\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### Initialize MTCNN Face Detection

In [20]:
device = 'cpu'

In [21]:
mtcnn = MTCNN(
    image_size=160,
    margin=20,
    keep_all=False,
    thresholds=[0.6, 0.7, 0.7],  # Lower thresholds = more detections
    device=device
)

In [22]:
for idx, frame in enumerate(frames):
    print(type(frames),frames.shape)
    break

<class 'numpy.ndarray'> (15, 224, 224, 3)

In [23]:
os.makedirs("detected_faces", exist_ok=True)

face_count = 0

for idx, frame in enumerate(frames):
    try:
        # Ensure correct format
        frame = frame.astype(np.uint8)

        #FACE DETECTION (PASS NUMPY IMAGE DIRECTLY)
        face = mtcnn(frame)

        if face is not None:
            # face is [3, 160, 160] tensor
            face_img = face.permute(1, 2, 0).numpy()
            face_img = (face_img * 255).astype(np.uint8)

            cv2.imwrite(
                f"detected_faces_{face_count}.jpg",
                cv2.cvtColor(face_img, cv2.COLOR_RGB2BGR)
            )

            face_count += 1

    except Exception as e:
        print(f"Skipped frame {idx}: {e}")

print("Total faces detected:", face_count)

Total faces detected: 15

# Step 3: Visualize face crops

In [28]:
face_dir = "detected_faces"

for f in os.listdir(face_dir):
    if not f.lower().endswith((".jpg", ".jpeg", ".png")):
        continue  # skip non-image files 

    path = os.path.join(face_dir, f)
    img = cv2.imread(path)
    if img is None:
        print(f"Skipping unreadable file: {f}")
        continue

    cv2.imshow("Face Image", img)
    cv2.waitKey(0)           
    cv2.destroyAllWindows()

# Step-4 : Face Cropped Frames(Boundary Box Method)

In [24]:
os.makedirs("cropped_faces", exist_ok=True)
cropped_faces = []

def extract_faces(frames, mtcnn, min_face_size=40):
    face_count = 0

    for idx, frame in enumerate(frames):
        try:
            frame = frame.astype(np.uint8)

            boxes, probs = mtcnn.detect(frame)

            if boxes is None:
                print(f"No face in frame {idx}")
                continue

            x1, y1, x2, y2 = boxes[0].astype(int)

            h, w, _ = frame.shape
            x1, y1 = max(0, x1), max(0, y1)
            x2, y2 = min(w, x2), min(h, y2)

            if (x2 - x1) < min_face_size or (y2 - y1) < min_face_size:
                print(f"Face too small in frame {idx}")
                continue

            face_crop = frame[y1:y2, x1:x2]

            if face_crop.size == 0:
                print(f"Empty crop in frame {idx}")
                continue

            face_crop = cv2.resize(face_crop, (160, 160))

            #save_path = f"cropped_faces/_{face_count}.jpg" --->Not Recommended, it'll create issues during training, crash 
            #cv2.imwrite(save_path, cv2.cvtColor(face_crop, cv2.COLOR_RGB2BGR))

            cropped_faces.append(face_crop)
            face_count += 1

        except Exception as e:
            print(f"Skipped Frame {idx}: {e}")

    if len(cropped_faces) == 0:
        return None

    return np.array(cropped_faces)

In [25]:
faces = extract_faces(frames, mtcnn)

if faces is None:
    print("No faces extracted")
else:
    print("Total number of cropped faces:", len(faces))

Total number of cropped faces: 15

In [26]:
print(len(cropped_faces))

15

In [27]:
print(type(frames), frames.shape)
faces = extract_faces(frames, mtcnn)
faces = faces.astype(np.float32)/255.0
print("Faces:", None if faces is None else faces.shape)

<class 'numpy.ndarray'> (15, 224, 224, 3)
Faces: (30, 160, 160, 3)

In [28]:
print(faces[0].min(), faces[0].max())

0.06666667 0.9607843

## Compute Face-Only Pixel Differences

In [29]:
print(os.listdir("cropped_faces"))

['.ipynb_checkpoints', '1100011002', '1100011003', '1100011004', '1100011005', '1100011006', '1100011007', '1100011008', '1100011009', '1100011010', '1100011011', '1100011012', '1100011013', '1100011014', '1100011015', '1100011016', '1100011017', '1100011018', '1100011019', '1100011020', '1100011021', '1100011022', '1100011023', '1100011025', '1100011026', '1100011027', '1100011028', '1100011029', '1100011031', '1100011032', '1100011034', '1100011035', '1100011037', '1100011038', '1100011040', '1100011046', '1100011047', '1100011048', '1100011049', '1100011050', '1100011051', '1100011052', '1100011053', '1100011054', '1100011055', '1100011056', '1100011057', '1100011058', '1100011059', '1100011060', '1100011062', '1100011063', '1100011064', '1100011066', '1100011067', '1100011068', '1100011069', '1100011070', '1100011071', '1100011072', '1100011073', '1100011075', '1100011076', '1100011078', '1100011079', '1100011080', '1100011081', '1100011082', '1100011083', '1100012001', '1100012003', '1100012007', '1100012008', '1100012009', '1100012010', '1100012011', '1100012013', '1100012014', '1100012015', '1100012016', '1100012017', '1100012018', '1100012021', '1100012022', '1100012023', '1100012025', '1100012026', '1100012027', '1100012028', '1100012030', '1100012031', '1100012032', '1100012033', '1100012036', '1100012037', '1100012038', '1100012041', '1100012042', '1100012045', '1100012046', '1100012047', '1100012049', '1100012050', '1100012051', '1100012052', '1100012057', '1100012059', '1100012060', '1100012061', '1100012062', '1100012063', '1100012064', '1100012065', '1100012066', '1100012069', '1100021001', '1100021003', '1100021015', '1100021038', '1100021039', '1100021040', '1100021045', '1100021050', '1100021055', '1100022001', '1100022002', '1100022003', '1100022004', '1100022005', '1100022008', '1100022009', '1100022014', '1100022019', '1100022020', '1100022021', '1100022022', '1100022026', '1100022027', '1100022028', '1100022029', '1100022031', '1100022035', '1100022038', '1100022039', '1100022045', '1100022046', '1100022047', '1100022048', '1100022049', '1100022051', '1100022052', '1100022053', '1100022054', '1100022055', '1100022056', '1100022057', '1100041006', '1100041015', '1100041016', '1100041017', '1100041018', '1100041021', '1100041022', '1100041023', '1100041024', '1100041029', '1100041034', '1100041044', '1100041051', '1100041052', '1100042009', '1100042010', '1100042011', '1100042017', '1100042018', '1100042019', '1100042020', '1100042023', '1100042024', '1100042025', '1100042026', '1100042029', '1100042030', '1100042031', '1100042034', '1100042040', '1100042041', '1100042058', '1100042059', '1100042060', '1100051002', '1100051004', '1100051006', '1100051007', '1100051008', '1100051009', '1100051011', '1100051012', '1100051013', '1100051014', '1100051016', '1100051017', '1100051019', '1100051020', '1100051021', '1100051022', '1100051023', '1100051024', '1100051025', '1100051026', '1100051028', '1100051029', '1100051030', '1100051031', '1100051032', '1100051033', '1100051034', '1100051035', '1100051036', '1100051037', '1100051039', '1100051041', '1100051042', '1100051044', '1100051045', '1100051046', '1100051048', '1100051049', '1100051050', '1100051051', '1100051052', '1100051053', '1100051054', '1100051055', '1100051056', '1100051057', '1100051059', '1100051061', '1100051062', '1100051064', '1100051065', '1100051066', '1100051067', '1100051068', '1100051071', '1100051076', '1100051078', '1100051079', '1100052001', '1100052002', '1100052006', '1100052007', '1100052008', '1100052009', '1100052014', '1100052023', '1100052024', '1100052026', '1100052027', '1100052028', '1100052030', '1100052031', '1100052032', '1100052033', '1100052035', '1100052036', '1100052037', '1100052038', '1100052039', '1100052040', '1100052041', '1100052047', '1100052048', '1100052049', '1100052051', '1100052055', '1100052057', '1100052060', '1100052061', '1100052062', '1100052065', '1100052068', '1100052070', '1100061009', '1100061010', '1100061011', '1100061012', '1100061013', '1100061015', '1100061016', '1100061018', '1100061019', '1100061022', '1100061023', '1100061025', '1100061027', '1100061028', '1100061030', '1100061031', '1100061032', '1100061033', '1100061034', '1100061035', '1100061036', '1100061038', '1100061039', '1100061040', '1100061042', '1100061043', '1100061044', '1100061046', '1100061047', '1100061048', '1100061049', '1100061050', '1100061051', '1100061053', '1100061057', '1100061058', '1100061061', '1100061063', '1100061064', '1100061067', '1100061068', '1100061069', '1100061073', '1100061074', '1100061077', '1100061078', '1100062004', '1100062005', '1100062007', '1100062008', '1100062009', '1100062016', '1100062017', '1100062024', '1100062028', '1100062029', '1100062036', '1100062037', '1100062044', '1100062045', '1100062046', '1100062049', '1100062051', '1100062053', '1100062054', '1100062059', '1100062060', '1100062061', '1100062062', '1100062063', '1100062064', '1100062065', '1100062066', '1100062067', '1100062068', '1100062069', '1100062070', '1100062071', '1100062072', '1100071005', '1100071006', '1100071007', '1100071008', '1100071009', '1100071010', '1100071011', '1100071012', '1100071013', '1100071014', '1100071015', '1100071016', '1100071017', '1100071018', '1100071019', '1100071020', '1100071021', '1100071022', '1100071023', '1100071024', '1100071026', '1100071027', '1100071028', '1100071029', '1100071030', '1100071031', '1100071032', '1100071033', '1100071034', '1100071035', '1100071036', '1100071037', '1100071040', '1100071041', '1100071042', '1100071043', '1100071044', '1100071045', '1100071046', '1100071047', '1100071049', '1100071050', '1100071052', '1100071054', '1100071055', '1100071056', '1100071057', '1100071058', '1100071059', '1100071060', '1100071061', '1100071062', '1100071063', '1100071064', '1100071065', '1100071066', '1100071067', '1100071069', '1100071070', '1100071071', '1100071072', '1100071073', '1100071074', '1100071075', '1100071076', '1100071077', '1100071078', '1100071079', '1100071080', '1100071081', '1100072001', '1100072002', '1100072003', '1100072004', '1100072006', '1100072007', '1100072008', '1100072009', '1100072010', '1100072011', '1100072012', '1100072013', '1100072014', '1100072015', '1100072016', '1100072021', '1100072022', '1100072023', '1100072024', '1100072027', '1100072028', '1100072029', '1100072030', '1100072031', '1100072032', '1100072033', '1100072034', '1100072036', '1100072037', '1100072038', '1100072039', '1100072040', '1100072042', '1100072043', '1100072045', '1100072047', '1100072048', '1100072049', '1100072050', '1100072051', '1100072052', '1100072053', '1100072054', '1100072056', '1100072057', '1100072058', '1100072059', '1100072060', '1100072061', '1100072062', '1100072063', '1100072065', '1100072066', '1100072067', '1100072068', '1100072069', '1100072070', '1100072071', '1100072072', '1100072073', '1100072074', '1100072075', '1100072076', '1100072077', '1100072078', '1100072079', '1100072080', '1100072081', '1100072082', '1100072083', '1100072084', '1100072085', '1100081044', '1100081045', '1100081046', '1100081047', '1100081048', '1100082002', '1100082003', '1100082018', '1100082027', '1100102003', '1100111001', '1100111002', '1100111003', '1100111008', '1100111009', '1100111010', '1100111011', '1100111012', '1100111013', '1100111014', '1100111016', '1100111017', '1100111018', '1100111019', '1100111021', '1100111023', '1100111025', '1100111026', '1100111027', '1100111029', '1100111030', '1100111032', '1100112001', '1100112002', '1100112003', '1100112004', '1100112006', '1100112007', '1100112008', '1100112009', '1100112010', '1100112011', '1100112012', '1100112013', '1100112014', '1100112015', '1100112016', '1100112017', '1100112018', '1100112021', '1100112022', '1100112024', '1100112025', '1100112026', '1100112029', '1100112030', '1100112033', '1100112035', '1100112036', '1100112037', '1100112038', '1100112039', '1100112040', '1100112041', '1100112042', '1100112043', '1100112044', '1100112045', '1100112047', '1100112048', '1100112051', '1100112052', '1100112053', '1100112056', '1100112057', '1100112058', '1100112059', '1100112060', '1100112061', '1100112062', '1100112063', '1100112064', '1100112065', '1100112066', '1100112068', '1100121002', '1100121003', '1100121004', '1100121005', '1100121006', '1100121007', '1100121008', '1100121009', '1100121010', '1100121011', '1100121012', '1100121015', '1100121016', '1100121017', '1100121018', '1100121019', '1100121020', '1100121024', '1100121025', '1100121028', '1100121031', '1100121032', '1100121033', '1100121034', '1100121035', '1100121036', '1100121038', '1100121040', '1100121041', '1100121042', '1100121044', '1100121045', '1100121047', '1100121049', '1100121050', '1100121052', '1100121053', '1100121054', '1100121056', '1100121057', '1100121059', '1100121060', '1100121061', '1100121064', '1100122001', '1100122002', '1100122003', '1100122005', '1100122006', '1100122007', '1100122008', '1100122009', '1100122010', '1100122011', '1100122012', '1100122013', '1100122014', '1100122015', '1100122017', '1100122018', '1100122019', '1100122020', '1100122021', '1100122023', '1100122024', '1100122025', '1100122026', '1100122031', '1100122032', '1100122033', '1100122034', '1100122035', '1100122036', '1100122037', '1100122038', '1100122039', '1100122040', '1100122041', '1100122045', '1100122047', '1100122048', '1100122050', '1100122051', '1100122052', '1100122053', '1100122054', '1100122056', '1100131006', '1100131007', '1100131009', '1100131010', '1100131011', '1100131012', '1100131017', '1100131019', '1100141001', '1100141002', '1100141003', '1100141004', '1100141005', '1100141006', '1100141007', '1100141008', '1100141009', '1100141010', '1100141011', '1100141012', '1100141013', '1100141014', '1100141015', '1100141016', '1100141017', '1100141019', '1100141020', '1100141021', '1100141023', '1100141027', '1100141028', '1100141029', '1100141030', '1100141031', '1100141032', '1100141033', '1100141034', '1100141035', '1100141036', '1100141039', '1100141040', '1100141042', '1100141044', '1100141045', '1100141046', '1100141049', '1100141050', '1100141052', '1100141053', '1100141054', '1100141055', '1100141056', '1100141057', '1100142002', '1100142003', '1100142004', '1100142007', '1100142008', '1100142009', '1100142010', '1100142011', '1100142013', '1100142014', '1100142015', '1100142017', '1100142018', '1100142019', '1100142021', '1100142022', '1100142023', '1100142024', '1100142027', '1100142028', '1100142029', '1100142030', '1100142031', '1100142032', '1100142033', '1100142034', '1100142035', '1100142038', '1100142041', '1100142043', '1100142044', '1100142045', '1100142046', '1100142048', '1100142049', '1100142050', '1100142051', '1100142052', '1100142053', '1100142056', '1100142057', '1100142058', '1100142059', '1100142060', '1100151003', '1100151004', '1100151008', '1100151009', '1100151010', '1100151011', '1100151012', '1100151013', '1100151014', '1100151015', '1100151016', '1100151017', '1100151018', '1100151019', '1100151020', '1100151021', '1100151022', '1100151023', '1100151024', '1100151028', '1100151030', '1100151032', '1100151033', '1100151035', '1100151037', '1100151038', '1100151039', '1100151040', '1100151042', '1100151043', '1100151044', '1100151047', '1100151049', '1100151050', '1100151051', '1100151052', '1100151054', '1100151055', '1100151056', '1100151057', '1100151058', '1100151062', '1100152001', '1100152004', '1100152005', '1100152006', '1100152008', '1100152009', '1100152010', '1100152013', '1100152014', '1100152015', '1100152017', '1100152019', '1100152020', '1100152022', '1100152024', '1100152025', '1100152026', '1100152027', '1100152031', '1100152032', '1100152039', '1100152040', '1100152041', '1100152042', '1100152043', '1100152048', '1100152049', '1100152050', '1100152051', '1100152055', '1100152056', '1100152061', '1100152062', '1100152067', '1100152069', '1100152070', '1100161002', '1100161004', '1100161011', '1100161012', '1100161013', '1100161014', '1100161015', '1100161016', '1100161020', '1100161021', '1100161022', '1100161023', '1100161028', '1100161029', '1100161032', '1100161035', '1100161036', '1100161038', '1100161039', '1100161041', '1100161043', '1100161044', '1100161045', '1100161046', '1100161048', '1100161050', '1100161053', '1100162005', '1100162007', '1100162011', '1100162016', '1100171001', '1100171002', '1100171004', '1100171005', '1100171007', '1100171008', '1100171009', '1100171010', '1100171011', '1100171012', '1100171013', '1100171015', '1100171016', '1100171017', '1100171019', '1100171021', '1100171022', '1100171023', '1100171031', '1100171035', '1100171036', '1100171038', '1100171039', '1100171040', '1100171041', '1100171043', '1100171045', '1100171049', '1100171055', '1100171056', '1100171057', '1100171059', '1100171061', '1100171063', '1100171064', '1100171065', '1100171067', '1100171069', '1100171070', '1100171071', '1100171072', '1100171073', '1100171074', '1100171075', '1100171076', '1100171077', '1100171078', '1100171080', '1100171083', '1100172003', '1100172004', '1100172007', '1100172012', '1100172013', '1100172014', '1100172015', '1100172016', '1100172017', '1100172018', '1100172020', '1100172021', '1100172022', '1100172026', '1100172028', '1100172030', '1100172032', '1100172033', '1100172034', '1100172035', '1100172037', '1100172039', '1100172042', '1100172043', '1100172047', '1100172050', '1100172058', '1100172063', '1100172066', '1100411010', '1100411011', '1100411012', '1100411013', '1100411015', '1100411016', '1100411018', '1100411020', '1100411023', '1100411036', '1100411041', '1100411045', '1100411047', '1100411048', '1100411049', '1100411050', '1100411051', '1100411053', '1100411054', '1100411055', '1100411057', '1100412001', '1100412003', '1100412010', '1100412018', '1100412033', '1100412038', '1100412039', '1100412040', '1110031003', '1110031007', '1110031010', '1110031011', '1110031012', '1110031014', '1110031019', '1110031020', '1110031021', '1110031025', '1110031027', '1110031031', '1110031033', '1110031037', '1110031038', '1110031039', '1110031040', '1110031042', '1110031048', '1110031049', '1110031050', '1110031056', '1110031061', '1110031062', '1110031063', '1110031064', '1110031065', '1110032002', '1110032004', '1110032006', '1110032008', '1110032010', '1110032014', '1110032015', '1110032018', '1110032019', '1110032020', '1110032021', '1110032022', '1110032023', '1110032024', '1110032025', '1110032027', '1110032029', '1110032031', '1110032032', '1110032033', '1110032034', '1110032036', '1110032037', '1110032042', '1110032043', '1110032045', '1110032047', '1110032048', '1110032049', '1110032050', '1110032051', '1110032052', '1110032053', '1110032055', '1110032056', '1110032058', '1110032059', '1110032060', '1110032061', '1110032062', '1110032063', '1813740111', '1813740112', '1813740115', '1813740116', '1813740118', '1813740119', '1813740122', '1813740123', '1813740124', '1813740126', '1813740127', '1813740128', '1813740131', '1813740133', '1813740135', '1813740137', '1813740138', '1813740143', '1813740144', '1813740149', '181374015', '1813740150', '1813740153', '1813740155', '1813740157', '1813740159', '181374016', '1813740162', '1813740164', '1813740165', '1813740167', '1813740168', '1813740169', '181374017', '1813740171', '1813740172', '1813740173', '1813740174', '1813740176', '1813740178', '1813740179', '1813740180', '1813740181', '1813740182', '1813740183', '1813740184', '1813740185', '181374019', '1813740210', '1813740211', '1813740212', '1813740213', '1813740214', '1813740218', '1813740219', '1813740220', '1813740221', '1813740224', '1813740225', '1813740226', '1813740227', '1813740229', '181374023', '1813740231', '1813740232', '1813740233', '1813740234', '1813740235', '1813740236', '1813740237', '1813740238', '181374024', '1813740240', '1813740241', '1813740242', '1813740243', '1813740245', '1813740249', '181374025', '1813740250', '1813740251', '1813740252', '1813740253', '1813740255', '1813740256', '1813740257', '1813740258', '1813740259', '181374026', '1813740260', '1813740261', '1813740262', '1813740263', '1813740264', '1813740265', '1813740266', '1813740267', '1813740268', '1813740269', '181374027', '1813740270', '1813740271', '1813740272', '1813740273', '1813740274', '1813740275', '1813740276', '1813740277', '1813740278', '1813740279', '181374028', '181374029', '2000481035', '2000481036', '2000481037', '2000481038', '2000481039', '2000481040', '2000481041', '2000481043', '2000481048', '2000482008', '2000482009', '2000482012', '2000482018', '2000482021', '2000482034', '2000482037', '2000482038', '2000482039', '2000482041', '2000482042', '2000482043', '2000482044', '2000482049', '2000482050', '2000482052', '2000482059', '2000482065', '2000482066', '2000482067', '2000482068', '2000482070', '2000491062', '2000491064', '2000491065', '2000491066', '2000491067', '2000491068', '2000491070', '2000491072', '2000491074', '2000491075', '2000491076', '2000491077', '2000491078', '2000491079', '2000501001', '2000501002', '2000501003', '2000501004', '2000501006', '2000501009', '2000501010', '2000501011', '2000501012', '2000501014', '2000501015', '2000501016', '2000501018', '2000501019', '2000501020', '2000501021', '2000501023', '2000501027', '2000501028', '2000501030', '2000501031', '2000501032', '2000501033', '2000501035', '2000501036', '2000501037', '2000501038', '2000501039', '2000501040', '2000501041', '2000501042', '2000501043', '2000501044', '2000501045', '2000501046', '2000501049', '2000501050', '2000501051', '2000501052', '2000501053', '2000501054', '2000501056', '2000501057', '2000501060', '2000501061', '2000501062', '2000501063', '2000501065', '2000501066', '2000501067', '2000501071', '2000501074', '2000501075', '2000501076', '2000501078', '2000502002', '2000502005', '2000502006', '2000502007', '2000502009', '2000502010', '2000502012', '2000502013', '2000502014', '2000502015', '2000502019', '2000502020', '2000502023', '2000502025', '2000502033', '2000502036', '2000502037', '2000502039', '2000502040', '2000502041', '2000502043', '2000502044', '2000502045', '2000502047', '2000502048', '2000502049', '2000502050', '2000502051', '2000502053', '2000502054', '2000502055', '2000502056', '2000502057', '2000502058', '2000502059', '2000502061', '2000502062', '2000502063', '2000502065', '2000502066', '2000502067', '2000502069', '2000502070', '2000502072', '2000502073', '2000502075', '2000502076', '2000502077', '2000502078', '2000502081', '2000502084', '2000502087', '2000502088', '2000502090', '2000541001', '2000541002', '2000541003', '2000541006', '2000541007', '2000541010', '2000541011', '2000541014', '2000541015', '2000541016', '2000541018', '2000541019', '2000541020', '2000541021', '2000541022', '2000541023', '2000541024', '2000541025', '2000541027', '2000541028', '2000541029', '2000541030', '2000541031', '2000541032', '2000541034', '2000541035', '2000541038', '2000541039', '2000541040', '2000541041', '2000541043', '2000541044', '2000541045', '2000541046', '2000541049', '2000541050', '2000541051', '2000541052', '2000541053', '2000541054', '2000541055', '2000541056', '2000541057', '2000541059', '2000541062', '2000541064', '2000541066', '2000541067', '2000541068', '2000541069', '2000541070', '2000541071', '2000541072', '2000541073', '2000541074', '2000541075', '2000541076', '2000541077', '2000541079', '2000541080', '2000541081', '2000542001', '2000542002', '2000542007', '2000542008', '2000542009', '2000542010', '2000542013', '2000542015', '2000542016', '2000542021', '2000542022', '2000542025', '2000542026', '2000542027', '2000542029', '2000542030', '2000542032', '2000542033', '2000542034', '2000542035', '2000542036', '2000542042', '2000542049', '2000542050', '2000542051', '2000542052', '2000542054', '2000542056', '2026140111', '2026140113', '2026140116', '2026140117', '2026140118', '2026140119', '2026140120', '2026140122', '2026140124', '2026140125', '2026140126', '2026140128', '2026140129', '2026140130', '2026140131', '2026140133', '202614013

In [30]:
face_dir = "cropped_faces"
face_files = sorted([f for f in os.listdir(face_dir) if f.endswith(".jpg")])

In [31]:
diffs = []

for i in range(len(face_files) - 1):
    path1 = os.path.join(face_dir, face_files[i])
    path2 = os.path.join(face_dir, face_files[i+1])
    
    face1 = cv2.imread(path1, cv2.IMREAD_GRAYSCALE)
    face2 = cv2.imread(path2, cv2.IMREAD_GRAYSCALE)

    # Skip if any image failed to load
    if face1 is None or face2 is None:
        print(f"Skipped pair: ({face_files[i]}, {face_files[i+1]})")
        continue

    # Ensure same shape
    if face1.shape != face2.shape:
        print(f"Skipped pair: ({face_files[i]}, {face_files[i+1]})")
        continue

    # Compute mean absolute difference
    diff = np.mean(np.abs(face1 - face2))
    diffs.append(diff)

if len(diffs) == 0:
    mean_diff = 0
else:
    mean_diff = np.mean(diffs)
print("Face-only mean pixel difference:", mean_diff)

Face-only mean pixel difference: 116.11891059027776

In [ ]:
cv2.imshow("Face 0", cropped_faces[0])
cv2.imshow("Face 1", cropped_faces[1])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [32]:
#image ∈ [0, 1]
faces = np.clip(faces, 0.0,1.0)

# Step-5 : Binary label engineering

In [33]:
# Load csv file
df = pd.read_csv("mind_w/Labels/TrainLabels.csv")
df.head()

           ClipID  Boredom  Engagement  Confusion  Frustration
0  1100011002.avi        0           2          0             0
1  1100011003.avi        0           2          0             0
2  1100011004.avi        0           3          0             0
3  1100011005.avi        0           3          0             0
4  1100011006.avi        0           3          0             0

### Check class balance(Mind Wandering vs Focused)

In [34]:
#Count how many clips would be Mind Wandering vs Focused
#remove .avi from clipID
df["ClipID"] = df["ClipID"].str.replace(".avi","",regex=False)

#remove extra spaces in column name
df.columns = df.columns.str.strip()

# Combine Rule
df["BinaryLabel"] = df.apply(
    lambda row : 1 if (row["Boredom"]+row["Confusion"]+row["Frustration"]) >= row["Engagement"]
    else 0, axis=1
)
# where 0-->Focused & 1-->Mind_Wandering

print(df["BinaryLabel"].value_counts())

BinaryLabel
0    3327
1    2031
Name: count, dtype: int64

### BinaryLabel mapping

In [35]:
#look up labels for each video
label_dict = dict(zip(df["ClipID"], df["BinaryLabel"]))
label_dict

{'1100011002': 0,
 '1100011003': 0,
 '1100011004': 0,
 '1100011005': 0,
 '1100011006': 0,
 '1100011007': 0,
 '1100011008': 0,
 '1100011009': 0,
 '1100011010': 0,
 '1100011011': 0,
 '1100011012': 1,
 '1100011013': 0,
 '1100011014': 0,
 '1100011015': 0,
 '1100011016': 0,
 '1100011017': 0,
 '1100011018': 0,
 '1100011019': 0,
 '1100011020': 0,
 '1100011021': 0,
 '1100011022': 0,
 '1100011023': 0,
 '1100011025': 0,
 '1100011026': 0,
 '1100011027': 0,
 '1100011028': 0,
 '1100011029': 0,
 '1100011031': 0,
 '1100011032': 0,
 '1100011034': 0,
 '1100011035': 0,
 '1100011037': 0,
 '1100011038': 0,
 '1100011040': 0,
 '1100011046': 0,
 '1100011047': 0,
 '1100011048': 1,
 '1100011049': 0,
 '1100011050': 0,
 '1100011051': 0,
 '1100011052': 0,
 '1100011053': 0,
 '1100011054': 0,
 '1100011055': 0,
 '1100011056': 0,
 '1100011057': 0,
 '1100011058': 0,
 '1100011059': 0,
 '1100011060': 1,
 '1100011062': 0,
 '1100011063': 0,
 '1100011064': 0,
 '1100011066': 0,
 '1100011067': 0,
 '1100011068': 0,
 '1100011069': 0,
 '1100011070': 0,
 '1100011071': 0,
 '1100011072': 0,
 '1100011073': 0,
 '1100011075': 0,
 '1100011076': 0,
 '1100011078': 0,
 '1100011079': 0,
 '1100011080': 0,
 '1100011081': 0,
 '1100011082': 0,
 '1100011083': 0,
 '1100012001': 0,
 '1100012003': 0,
 '1100012007': 0,
 '1100012008': 0,
 '1100012009': 0,
 '1100012010': 1,
 '1100012011': 0,
 '1100012013': 0,
 '1100012014': 0,
 '1100012015': 0,
 '1100012016': 0,
 '1100012017': 0,
 '1100012018': 0,
 '1100012021': 0,
 '1100012022': 0,
 '1100012023': 0,
 '1100012025': 0,
 '1100012026': 0,
 '1100012027': 0,
 '1100012028': 0,
 '1100012030': 0,
 '1100012031': 0,
 '1100012032': 0,
 '1100012033': 0,
 '1100012036': 0,
 '1100012037': 0,
 '1100012038': 0,
 '1100012041': 0,
 '1100012042': 0,
 '1100012045': 0,
 '1100012046': 0,
 '1100012047': 0,
 '1100012049': 0,
 '1100012050': 0,
 '1100012051': 0,
 '1100012052': 0,
 '1100012057': 1,
 '1100012059': 0,
 '1100012060': 0,
 '1100012061': 0,
 '1100012062': 0,
 '1100012063': 0,
 '1100012064': 0,
 '1100012065': 0,
 '1100012066': 0,
 '1100012069': 0,
 '1100021001': 0,
 '1100021003': 0,
 '1100021015': 1,
 '1100021038': 0,
 '1100021039': 1,
 '1100021040': 0,
 '1100021045': 0,
 '1100021050': 0,
 '1100021055': 1,
 '1100022001': 1,
 '1100022002': 1,
 '1100022003': 1,
 '1100022004': 1,
 '1100022005': 1,
 '1100022008': 1,
 '1100022009': 0,
 '1100022014': 0,
 '1100022019': 1,
 '1100022020': 0,
 '1100022021': 1,
 '1100022022': 1,
 '1100022026': 0,
 '1100022027': 1,
 '1100022028': 0,
 '1100022029': 0,
 '1100022031': 0,
 '1100022035': 0,
 '1100022038': 1,
 '1100022039': 0,
 '1100022045': 0,
 '1100022046': 0,
 '1100022047': 1,
 '1100022048': 1,
 '1100022049': 1,
 '1100022051': 1,
 '1100022052': 1,
 '1100022053': 1,
 '1100022054': 0,
 '1100022055': 0,
 '1100022056': 0,
 '1100022057': 0,
 '1100041006': 0,
 '1100041015': 0,
 '1100041016': 0,
 '1100041017': 1,
 '1100041018': 1,
 '1100041021': 0,
 '1100041022': 1,
 '1100041023': 1,
 '1100041024': 1,
 '1100041029': 0,
 '1100041034': 0,
 '1100041044': 0,
 '1100041051': 0,
 '1100041052': 0,
 '1100042009': 1,
 '1100042010': 1,
 '1100042011': 1,
 '1100042017': 1,
 '1100042018': 0,
 '1100042019': 0,
 '1100042020': 0,
 '1100042023': 1,
 '1100042024': 1,
 '1100042025': 0,
 '1100042026': 1,
 '1100042029': 0,
 '1100042030': 0,
 '1100042031': 1,
 '1100042034': 0,
 '1100042040': 0,
 '1100042041': 0,
 '1100042058': 1,
 '1100042059': 1,
 '1100042060': 1,
 '1100051002': 0,
 '1100051004': 1,
 '1100051006': 1,
 '1100051007': 1,
 '1100051008': 1,
 '1100051009': 1,
 '1100051011': 0,
 '1100051012': 0,
 '1100051013': 1,
 '1100051014': 0,
 '1100051016': 1,
 '1100051017': 1,
 '1100051019': 1,
 '1100051020': 1,
 '1100051021': 1,
 '1100051022': 1,
 '1100051023': 0,
 '1100051024': 1,
 '1100051025': 1,
 '1100051026': 1,
 '1100051028': 1,
 '1100051029': 1,
 '1100051030': 1,
 '1100051031': 1,
 '1100051032': 0,
 '1100051033': 1,
 '1100051034': 1,
 '1100051035': 1,
 '1100051036': 1,
 '1100051037': 1,
 '1100051039': 1,
 '1100051041': 0,
 '1100051042': 1,
 '1100051044': 0,
 '1100051045': 0,
 '1100051046': 0,
 '1100051048': 1,
 '1100051049': 1,
 '1100051050': 0,
 '1100051051': 0,
 '1100051052': 1,
 '1100051053': 1,
 '1100051054': 1,
 '1100051055': 0,
 '1100051056': 1,
 '1100051057': 1,
 '1100051059': 0,
 '1100051061': 1,
 '1100051062': 1,
 '1100051064': 0,
 '1100051065': 1,
 '1100051066': 1,
 '1100051067': 1,
 '1100051068': 0,
 '1100051071': 0,
 '1100051076': 1,
 '1100051078': 0,
 '1100051079': 0,
 '1100052001': 1,
 '1100052002': 1,
 '1100052006': 1,
 '1100052007': 1,
 '1100052008': 0,
 '1100052009': 0,
 '1100052014': 1,
 '1100052023': 1,
 '1100052024': 0,
 '1100052026': 0,
 '1100052027': 1,
 '1100052028': 0,
 '1100052030': 1,
 '1100052031': 0,
 '1100052032': 1,
 '1100052033': 0,
 '1100052035': 0,
 '1100052036': 1,
 '1100052037': 1,
 '1100052038': 1,
 '1100052039': 0,
 '1100052040': 1,
 '1100052041': 1,
 '1100052047': 0,
 '1100052048': 1,
 '1100052049': 0,
 '1100052051': 1,
 '1100052055': 0,
 '1100052057': 1,
 '1100052060': 0,
 '1100052061': 1,
 '1100052062': 1,
 '1100052065': 0,
 '1100052068': 1,
 '1100052070': 1,
 '1100061009': 0,
 '1100061010': 0,
 '1100061011': 0,
 '1100061012': 0,
 '1100061013': 0,
 '1100061015': 1,
 '1100061016': 0,
 '1100061018': 1,
 '1100061019': 0,
 '1100061022': 0,
 '1100061023': 0,
 '1100061025': 1,
 '1100061027': 0,
 '1100061028': 0,
 '1100061030': 0,
 '1100061031': 0,
 '1100061032': 0,
 '1100061033': 0,
 '1100061034': 0,
 '1100061035': 0,
 '1100061036': 0,
 '1100061038': 0,
 '1100061039': 0,
 '1100061040': 0,
 '1100061042': 0,
 '1100061043': 0,
 '1100061044': 0,
 '1100061046': 0,
 '1100061047': 0,
 '1100061048': 0,
 '1100061049': 0,
 '1100061050': 1,
 '1100061051': 0,
 '1100061053': 1,
 '1100061057': 0,
 '1100061058': 0,
 '1100061061': 0,
 '1100061063': 0,
 '1100061064': 0,
 '1100061067': 0,
 '1100061068': 0,
 '1100061069': 0,
 '1100061073': 0,
 '1100061074': 0,
 '1100061077': 0,
 '1100061078': 0,
 '1100062004': 0,
 '1100062005': 1,
 '1100062007': 0,
 '1100062008': 1,
 '1100062009': 0,
 '1100062016': 0,
 '1100062017': 0,
 '1100062024': 1,
 '1100062028': 1,
 '1100062029': 1,
 '1100062036': 1,
 '1100062037': 1,
 '1100062044': 1,
 '1100062045': 1,
 '1100062046': 1,
 '1100062049': 1,
 '1100062051': 1,
 '1100062053': 0,
 '1100062054': 1,
 '1100062059': 1,
 '1100062060': 1,
 '1100062061': 0,
 '1100062062': 0,
 '1100062063': 1,
 '1100062064': 1,
 '1100062065': 0,
 '1100062066': 1,
 '1100062067': 0,
 '1100062068': 1,
 '1100062069': 0,
 '1100062070': 1,
 '1100062071': 1,
 '1100062072': 1,
 '1100071005': 1,
 '1100071006': 1,
 '1100071007': 1,
 '1100071008': 0,
 '1100071009': 1,
 '1100071010': 1,
 '1100071011': 1,
 '1100071012': 0,
 '1100071013': 0,
 '1100071014': 0,
 '1100071015': 1,
 '1100071016': 0,
 '1100071017': 1,
 '1100071018': 0,
 '1100071019': 0,
 '1100071020': 1,
 '1100071021': 0,
 '1100071022': 1,
 '1100071023': 1,
 '1100071024': 1,
 '1100071026': 1,
 '1100071027': 1,
 '1100071028': 1,
 '1100071029': 1,
 '1100071030': 0,
 '1100071031': 1,
 '1100071032': 1,
 '1100071033': 1,
 '1100071034': 0,
 '1100071035': 0,
 '1100071036': 0,
 '1100071037': 1,
 '1100071040': 0,
 '1100071041': 1,
 '1100071042': 1,
 '1100071043': 1,
 '1100071044': 1,
 '1100071045': 1,
 '1100071046': 1,
 '1100071047': 1,
 '1100071049': 0,
 '1100071050': 0,
 '1100071052': 1,
 '1100071054': 0,
 '1100071055': 1,
 '1100071056': 1,
 '1100071057': 0,
 '1100071058': 1,
 '1100071059': 1,
 '1100071060': 0,
 '1100071061': 0,
 '1100071062': 1,
 '1100071063': 0,
 '1100071064': 0,
 '1100071065': 1,
 '1100071066': 1,
 '1100071067': 0,
 '1100071069': 0,
 '1100071070': 0,
 '1100071071': 1,
 '1100071072': 1,
 '1100071073': 0,
 '1100071074': 1,
 '1100071075': 1,
 '1100071076': 1,
 '1100071077': 0,
 '1100071078': 0,
 '1100071079': 0,
 '1100071080': 0,
 '1100071081': 0,
 '1100072001': 1,
 '1100072002': 0,
 '1100072003': 0,
 '1100072004': 1,
 '1100072006': 0,
 '1100072007': 0,
 '1100072008': 1,
 '1100072009': 0,
 '1100072010': 1,
 '1100072011': 0,
 '1100072012': 0,
 '1100072013': 0,
 '1100072014': 0,
 '1100072015': 1,
 '1100072016': 1,
 '1100072021': 1,
 '1100072022': 0,
 '1100072023': 0,
 '1100072024': 0,
 '1100072027': 0,
 '1100072028': 1,
 '1100072029': 0,
 '1100072030': 1,
 '1100072031': 1,
 '1100072032': 0,
 '1100072033': 0,
 '1100072034': 1,
 '1100072036': 1,
 '1100072037': 1,
 '1100072038': 1,
 '1100072039': 1,
 '1100072040': 0,
 '1100072042': 0,
 '1100072043': 1,
 '1100072045': 1,
 '1100072047': 0,
 '1100072048': 1,
 '1100072049': 0,
 '1100072050': 1,
 '1100072051': 0,
 '1100072052': 0,
 '1100072053': 0,
 '1100072054': 0,
 '1100072056': 1,
 '1100072057': 1,
 '1100072058': 0,
 '1100072059': 1,
 '1100072060': 1,
 '1100072061': 1,
 '1100072062': 1,
 '1100072063': 0,
 '1100072065': 1,
 '1100072066': 0,
 '1100072067': 1,
 '1100072068': 0,
 '1100072069': 0,
 '1100072070': 1,
 '1100072071': 1,
 '1100072072': 0,
 '1100072073': 1,
 '1100072074': 0,
 '1100072075': 1,
 '1100072076': 1,
 '1100072077': 0,
 '1100072078': 0,
 '1100072079': 0,
 '1100072080': 1,
 '1100072081': 0,
 '1100072082': 0,
 '1100072083': 0,
 '1100072084': 0,
 '1100072085': 1,
 '1100081044': 1,
 '1100081045': 0,
 '1100081046': 1,
 '1100081047': 0,
 '1100081048': 0,
 '1100082002': 0,
 '1100082003': 0,
 '1100082018': 1,
 '1100082027': 0,
 '1100102003': 1,
 '1100111001': 0,
 '1100111002': 0,
 '1100111003': 1,
 '1100111008': 0,
 '1100111009': 0,
 '1100111010': 0,
 '1100111011': 0,
 '1100111012': 0,
 '1100111013': 1,
 '1100111014': 1,
 '1100111016': 0,
 '1100111017': 0,
 '1100111018': 1,
 '1100111019': 0,
 '1100111021': 0,
 '1100111023': 0,
 '1100111025': 0,
 '1100111026': 0,
 '1100111027': 1,
 '1100111029': 1,
 '1100111030': 0,
 '1100111032': 0,
 '1100112001': 0,
 '1100112002': 1,
 '1100112003': 0,
 '1100112004': 0,
 '1100112006': 0,
 '1100112007': 0,
 '1100112008': 0,
 '1100112009': 0,
 '1100112010': 0,
 '1100112011': 1,
 '1100112012': 0,
 '1100112013': 0,
 '1100112014': 0,
 '1100112015': 0,
 '1100112016': 0,
 '1100112017': 0,
 '1100112018': 0,
 '1100112021': 1,
 '1100112022': 0,
 '1100112024': 0,
 '1100112025': 0,
 '1100112026': 1,
 '1100112029': 0,
 '1100112030': 0,
 '1100112033': 0,
 '1100112035': 0,
 '1100112036': 0,
 '1100112037': 0,
 '1100112038': 1,
 '1100112039': 0,
 '1100112040': 0,
 '1100112041': 0,
 '1100112042': 0,
 '1100112043': 0,
 '1100112044': 0,
 '1100112045': 1,
 '1100112047': 0,
 '1100112048': 0,
 '1100112051': 0,
 '1100112052': 0,
 '1100112053': 0,
 '1100112056': 0,
 '1100112057': 0,
 '1100112058': 0,
 '1100112059': 0,
 '1100112060': 0,
 '1100112061': 0,
 '1100112062': 1,
 '1100112063': 1,
 '1100112064': 0,
 '1100112065': 1,
 '1100112066': 0,
 '1100112068': 0,
 '1100121002': 0,
 '1100121003': 0,
 '1100121004': 0,
 '1100121005': 0,
 '1100121006': 0,
 '1100121007': 0,
 '1100121008': 0,
 '1100121009': 0,
 '1100121010': 0,
 '1100121011': 0,
 '1100121012': 0,
 '1100121015': 1,
 '1100121016': 1,
 '1100121017': 0,
 '1100121018': 1,
 '1100121019': 0,
 '1100121020': 0,
 '1100121024': 1,
 '1100121025': 1,
 '1100121028': 0,
 '1100121031': 1,
 '1100121032': 0,
 '1100121033': 0,
 '1100121034': 1,
 '1100121035': 0,
 '1100121036': 0,
 '1100121038': 0,
 '1100121040': 0,
 '1100121041': 1,
 '1100121042': 0,
 '1100121044': 0,
 '1100121045': 0,
 '1100121047': 0,
 '1100121049': 0,
 '1100121050': 1,
 '1100121052': 0,
 '1100121053': 0,
 '1100121054': 0,
 '1100121056': 0,
 '1100121057': 0,
 '1100121059': 0,
 '1100121060': 0,
 '1100121061': 1,
 '1100121064': 0,
 '1100122001': 0,
 '1100122002': 0,
 '1100122003': 0,
 '1100122005': 0,
 '1100122006': 0,
 '1100122007': 0,
 '1100122008': 1,
 '1100122009': 0,
 '1100122010': 0,
 '1100122011': 0,
 '1100122012': 0,
 '1100122013': 0,
 '1100122014': 0,
 '1100122015': 0,
 '1100122017': 0,
 '1100122018': 0,
 '1100122019': 0,
 '1100122020': 0,
 '1100122021': 1,
 '1100122023': 0,
 '1100122024': 0,
 '1100122025': 0,
 '1100122026': 0,
 '1100122031': 0,
 '1100122032': 0,
 '1100122033': 0,
 '1100122034': 0,
 '1100122035': 1,
 '1100122036': 0,
 '1100122037': 0,
 '1100122038': 0,
 '1100122039': 0,
 '1100122040': 0,
 '1100122041': 0,
 '1100122045': 1,
 '1100122047': 0,
 '1100122048': 0,
 '1100122050': 0,
 '1100122051': 0,
 '1100122052': 0,
 '1100122053': 0,
 '1100122054': 0,
 '1100122056': 1,
 '1100131006': 0,
 '1100131007': 0,
 '1100131009': 0,
 '1100131010': 0,
 '1100131011': 0,
 '1100131012': 0,
 '1100131017': 1,
 '1100131019': 0,
 '1100141001': 0,
 '1100141002': 1,
 '1100141003': 0,
 '1100141004': 0,
 '1100141005': 0,
 '1100141006': 1,
 '1100141007': 0,
 '1100141008': 0,
 '1100141009': 0,
 '1100141010': 0,
 '1100141011': 1,
 '1100141012': 1,
 '1100141013': 1,
 '1100141014': 1,
 '1100141015': 1,
 '1100141016': 0,
 '1100141017': 1,
 '1100141019': 1,
 '1100141020': 1,
 '1100141021': 1,
 '1100141023': 0,
 '1100141027': 1,
 '1100141028': 1,
 '1100141029': 1,
 '1100141030': 1,
 '1100141031': 1,
 '1100141032': 1,
 '1100141033': 1,
 '1100141034': 1,
 '1100141035': 1,
 '1100141036': 1,
 '1100141039': 1,
 '1100141040': 1,
 '1100141042': 1,
 '1100141044': 0,
 '1100141045': 1,
 '1100141046': 1,
 '1100141049': 1,
 '1100141050': 1,
 '1100141052': 1,
 '1100141053': 1,
 '1100141054': 0,
 '1100141055': 0,
 '1100141056': 1,
 '1100141057': 1,
 '1100142002': 0,
 '1100142003': 1,
 '1100142004': 1,
 '1100142007': 1,
 '1100142008': 0,
 '1100142009': 1,
 '1100142010': 1,
 '1100142011': 1,
 '1100142013': 1,
 '1100142014': 1,
 '1100142015': 0,
 '1100142017': 0,
 '1100142018': 1,
 '1100142019': 1,
 '1100142021': 1,
 '1100142022': 1,
 '1100142023': 1,
 '1100142024': 0,
 '1100142027': 0,
 '1100142028': 1,
 '1100142029': 0,
 '1100142030': 0,
 '1100142031': 0,
 '1100142032': 0,
 '1100142033': 1,
 '1100142034': 0,
 '1100142035': 0,
 '1100142038': 0,
 '1100142041': 0,
 '1100142043': 1,
 '1100142044': 1,
 '1100142045': 0,
 '1100142046': 0,
 '1100142048': 0,
 '1100142049': 0,
 '1100142050': 1,
 '1100142051': 1,
 '1100142052': 1,
 '1100142053': 0,
 '1100142056': 0,
 '1100142057': 0,
 '1100142058': 0,
 '1100142059': 1,
 '1100142060': 1,
 '1100151003': 0,
 '1100151004': 0,
 '1100151008': 1,
 '1100151009': 1,
 '1100151010': 1,
 '1100151011': 1,
 '1100151012': 1,
 '1100151013': 1,
 '1100151014': 0,
 '1100151015': 0,
 '1100151016': 1,
 '1100151017': 1,
 '1100151018': 1,
 '1100151019': 0,
 '1100151020': 1,
 '1100151021': 0,
 '1100151022': 0,
 '1100151023': 1,
 '1100151024': 1,
 '1100151028': 1,
 '1100151030': 1,
 '1100151032': 0,
 '1100151033': 0,
 '1100151035': 0,
 '1100151037': 0,
 '1100151038': 0,
 '1100151039': 0,
 '1100151040': 0,
 '1100151042': 0,
 '1100151043': 1,
 '1100151044': 1,
 '1100151047': 1,
 '1100151049': 0,
 '1100151050': 1,
 '1100151051': 1,
 '1100151052': 0,
 '1100151054': 0,
 '1100151055': 0,
 '1100151056': 0,
 '1100151057': 1,
 '1100151058': 0,
 '1100151062': 0,
 '1100152001': 1,
 '1100152004': 0,
 '1100152005': 0,
 '1100152006': 0,
 '1100152008': 1,
 '1100152009': 0,
 '1100152010': 1,
 '1100152013': 0,
 '1100152014': 1,
 '1100152015': 0,
 '1100152017': 1,
 '1100152019': 0,
 '1100152020': 0,
 '1100152022': 1,
 '1100152024': 1,
 '1100152025': 0,
 '1100152026': 1,
 '1100152027': 0,
 '1100152031': 1,
 '1100152032': 0,
 '1100152039': 1,
 '1100152040': 0,
 '1100152041': 1,
 '1100152042': 0,
 '1100152043': 1,
 '1100152048': 0,
 '1100152049': 1,
 '1100152050': 1,
 '1100152051': 1,
 '1100152055': 0,
 '1100152056': 0,
 '1100152061': 1,
 '1100152062': 1,
 '1100152067': 1,
 '1100152069': 0,
 '1100152070': 1,
 '1100161002': 0,
 '1100161004': 0,
 '1100161011': 0,
 '1100161012': 0,
 '1100161013': 0,
 '1100161014': 0,
 '1100161015': 0,
 '1100161016': 1,
 '1100161020': 0,
 '1100161021': 0,
 '1100161022': 1,
 '1100161023': 1,
 '1100161028': 1,
 '1100161029': 1,
 '1100161032': 1,
 '1100161035': 0,
 '1100161036': 1,
 '1100161038': 1,
 '1100161039': 0,
 '1100161041': 0,
 '1100161043': 0,
 '1100161044': 1,
 '1100161045': 1,
 '1100161046': 0,
 '1100161048': 1,
 '1100161050': 0,
 '1100161053': 0,
 '1100162005': 1,
 '1100162007': 0,
 '1100162011': 0,
 '1100162016': 1,
 '1100171001': 1,
 '1100171002': 0,
 '1100171004': 1,
 '1100171005': 0,
 '1100171007': 0,
 '1100171008': 1,
 '1100171009': 1,
 '1100171010': 1,
 '1100171011': 0,
 '1100171012': 0,
 '1100171013': 0,
 '1100171015': 0,
 '1100171016': 1,
 '1100171017': 0,
 '1100171019': 1,
 '1100171021': 1,
 '1100171022': 1,
 '1100171023': 0,
 '1100171031': 1,
 '1100171035': 1,
 '1100171036': 1,
 '1100171038': 0,
 '1100171039': 0,
 '1100171040': 1,
 '1100171041': 1,
 '1100171043': 1,
 '1100171045': 0,
 '1100171049': 0,
 '1100171055': 0,
 '1100171056': 0,
 '1100171057': 0,
 '1100171059': 1,
 '1100171061': 0,
 '1100171063': 0,
 '1100171064': 0,
 '1100171065': 0,
 '1100171067': 1,
 '1100171069': 0,
 '1100171070': 0,
 '1100171071': 1,
 '1100171072': 0,
 '1100171073': 0,
 '1100171074': 0,
 '1100171075': 1,
 '1100171076': 1,
 '1100171077': 0,
 '1100171078': 1,
 '1100171080': 0,
 '1100171083': 0,
 '1100172003': 0,
 '1100172004': 1,
 '1100172007': 1,
 '1100172012': 1,
 '1100172013': 0,
 '1100172014': 1,
 '1100172015': 1,
 '1100172016': 1,
 '1100172017': 1,
 '1100172018': 1,
 '1100172020': 0,
 '1100172021': 0,
 '1100172022': 0,
 '1100172026': 1,
 '1100172028': 0,
 '1100172030': 0,
 '1100172032': 0,
 '1100172033': 1,
 '1100172034': 1,
 '1100172035': 0,
 '1100172037': 0,
 '1100172039': 0,
 '1100172042': 1,
 '1100172043': 1,
 '1100172047': 1,
 '1100172050': 0,
 '1100172058': 1,
 '1100172063': 1,
 '1100172066': 1,
 '1100411010': 1,
 '1100411011': 0,
 '1100411012': 0,
 '1100411013': 0,
 '1100411015': 0,
 '1100411016': 0,
 '1100411018': 0,
 '1100411020': 0,
 '1100411023': 0,
 '1100411036': 1,
 '1100411041': 1,
 '1100411045': 0,
 '1100411047': 1,
 '1100411048': 1,
 '1100411049': 0,
 '1100411050': 1,
 '1100411051': 0,
 '1100411053': 1,
 '1100411054': 0,
 '1100411055': 1,
 '1100411057': 1,
 '1100412001': 0,
 '1100412003': 1,
 '1100412010': 1,
 '1100412018': 1,
 '1100412033': 1,
 '1100412038': 1,
 '1100412039': 1,
 '1100412040': 1,
 '1110031003': 1,
 '1110031007': 1,
 '1110031010': 1,
 '1110031011': 1,
 '1110031012': 1,
 '1110031014': 1,
 '1110031019': 0,
 '1110031020': 1,
 '1110031021': 1,
 '1110031025': 1,
 '1110031027': 1,
 '1110031031': 1,
 ...}

### Assign labels to cropped face frames

In [36]:
print(os.cpu_count())

8

In [37]:
save_root = "cropped_faces"
dataset = [] #(image_path,label)

for subject_id in os.listdir(Train_dataset_path):
    subject_path = os.path.join(Train_dataset_path, subject_id)

    if not os.path.isdir(subject_path):
        continue

    for clip_id in os.listdir(subject_path):
        clip_path = os.path.join(subject_path, clip_id)

        if not os.path.isdir(clip_path):
            continue

        label = label_dict.get(clip_id)
        if label is None:
            continue ## skip unlabeled clips
        
        print(f"Processing clip: {clip_id} → Label: {label}")

        #creating a folder for this clip
        save_dir = os.path.join(save_root, clip_id)
        os.makedirs(save_dir, exist_ok=True)
        
        # suppose 'frames' is a list of cropped faces for this clip
        for i, face in enumerate(frames):  # frames extracted from video
            save_path = os.path.join(save_dir, f"face_{i}.jpg")
            cv2.imwrite(save_path, face)

            # store in dataset immediately
            dataset.append((save_path, label))

Processing clip: 1100011002 → Label: 0
Processing clip: 1100011003 → Label: 0
Processing clip: 1100011004 → Label: 0
Processing clip: 1100011005 → Label: 0
Processing clip: 1100011006 → Label: 0
Processing clip: 1100011007 → Label: 0
Processing clip: 1100011008 → Label: 0
Processing clip: 1100011009 → Label: 0
Processing clip: 1100011010 → Label: 0
Processing clip: 1100011011 → Label: 0
Processing clip: 1100011012 → Label: 1
Processing clip: 1100011013 → Label: 0
Processing clip: 1100011014 → Label: 0
Processing clip: 1100011015 → Label: 0
Processing clip: 1100011016 → Label: 0
Processing clip: 1100011017 → Label: 0
Processing clip: 1100011018 → Label: 0
Processing clip: 1100011019 → Label: 0
Processing clip: 1100011020 → Label: 0
Processing clip: 1100011021 → Label: 0
Processing clip: 1100011022 → Label: 0
Processing clip: 1100011023 → Label: 0
Processing clip: 1100011025 → Label: 0
Processing clip: 1100011026 → Label: 0
Processing clip: 1100011027 → Label: 0
Processing clip: 1100011028 → Label: 0
Processing clip: 1100011029 → Label: 0
Processing clip: 1100011031 → Label: 0
Processing clip: 1100011032 → Label: 0
Processing clip: 1100011034 → Label: 0
Processing clip: 1100011035 → Label: 0
Processing clip: 1100011037 → Label: 0
Processing clip: 1100011038 → Label: 0
Processing clip: 1100011040 → Label: 0
Processing clip: 1100011046 → Label: 0
Processing clip: 1100011047 → Label: 0
Processing clip: 1100011048 → Label: 1
Processing clip: 1100011049 → Label: 0
Processing clip: 1100011050 → Label: 0
Processing clip: 1100011051 → Label: 0
Processing clip: 1100011052 → Label: 0
Processing clip: 1100011053 → Label: 0
Processing clip: 1100011054 → Label: 0
Processing clip: 1100011055 → Label: 0
Processing clip: 1100011056 → Label: 0
Processing clip: 1100011057 → Label: 0
Processing clip: 1100011058 → Label: 0
Processing clip: 1100011059 → Label: 0
Processing clip: 1100011060 → Label: 1
Processing clip: 1100011062 → Label: 0
Processing clip: 1100011063 → Label: 0
Processing clip: 1100011064 → Label: 0
Processing clip: 1100011066 → Label: 0
Processing clip: 1100011067 → Label: 0
Processing clip: 1100011068 → Label: 0
Processing clip: 1100011069 → Label: 0
Processing clip: 1100011070 → Label: 0
Processing clip: 1100011071 → Label: 0
Processing clip: 1100011072 → Label: 0
Processing clip: 1100011073 → Label: 0
Processing clip: 1100011075 → Label: 0
Processing clip: 1100011076 → Label: 0
Processing clip: 1100011078 → Label: 0
Processing clip: 1100011079 → Label: 0
Processing clip: 1100011080 → Label: 0
Processing clip: 1100011081 → Label: 0
Processing clip: 1100011082 → Label: 0
Processing clip: 1100011083 → Label: 0
Processing clip: 1100012001 → Label: 0
Processing clip: 1100012003 → Label: 0
Processing clip: 1100012007 → Label: 0
Processing clip: 1100012008 → Label: 0
Processing clip: 1100012009 → Label: 0
Processing clip: 1100012010 → Label: 1
Processing clip: 1100012011 → Label: 0
Processing clip: 1100012013 → Label: 0
Processing clip: 1100012014 → Label: 0
Processing clip: 1100012015 → Label: 0
Processing clip: 1100012016 → Label: 0
Processing clip: 1100012017 → Label: 0
Processing clip: 1100012018 → Label: 0
Processing clip: 1100012021 → Label: 0
Processing clip: 1100012022 → Label: 0
Processing clip: 1100012023 → Label: 0
Processing clip: 1100012025 → Label: 0
Processing clip: 1100012026 → Label: 0
Processing clip: 1100012027 → Label: 0
Processing clip: 1100012028 → Label: 0
Processing clip: 1100012030 → Label: 0
Processing clip: 1100012031 → Label: 0
Processing clip: 1100012032 → Label: 0
Processing clip: 1100012033 → Label: 0
Processing clip: 1100012036 → Label: 0
Processing clip: 1100012037 → Label: 0
Processing clip: 1100012038 → Label: 0
Processing clip: 1100012041 → Label: 0
Processing clip: 1100012042 → Label: 0
Processing clip: 1100012045 → Label: 0
Processing clip: 1100012046 → Label: 0
Processing clip: 1100012047 → Label: 0
Processing clip: 1100012049 → Label: 0
Processing clip: 1100012050 → Label: 0
Processing clip: 1100012051 → Label: 0
Processing clip: 1100012052 → Label: 0
Processing clip: 1100012057 → Label: 1
Processing clip: 1100012059 → Label: 0
Processing clip: 1100012060 → Label: 0
Processing clip: 1100012061 → Label: 0
Processing clip: 1100012062 → Label: 0
Processing clip: 1100012063 → Label: 0
Processing clip: 1100012064 → Label: 0
Processing clip: 1100012065 → Label: 0
Processing clip: 1100012066 → Label: 0
Processing clip: 1100012069 → Label: 0
Processing clip: 1100021001 → Label: 0
Processing clip: 1100021003 → Label: 0
Processing clip: 1100021015 → Label: 1
Processing clip: 1100021038 → Label: 0
Processing clip: 1100021039 → Label: 1
Processing clip: 1100021040 → Label: 0
Processing clip: 1100021045 → Label: 0
Processing clip: 1100021050 → Label: 0
Processing clip: 1100021055 → Label: 1
Processing clip: 1100022001 → Label: 1
Processing clip: 1100022002 → Label: 1
Processing clip: 1100022003 → Label: 1
Processing clip: 1100022004 → Label: 1
Processing clip: 1100022005 → Label: 1
Processing clip: 1100022008 → Label: 1
Processing clip: 1100022009 → Label: 0
Processing clip: 1100022014 → Label: 0
Processing clip: 1100022019 → Label: 1
Processing clip: 1100022020 → Label: 0
Processing clip: 1100022021 → Label: 1
Processing clip: 1100022022 → Label: 1
Processing clip: 1100022026 → Label: 0
Processing clip: 1100022027 → Label: 1
Processing clip: 1100022028 → Label: 0
Processing clip: 1100022029 → Label: 0
Processing clip: 1100022031 → Label: 0
Processing clip: 1100022035 → Label: 0
Processing clip: 1100022038 → Label: 1
Processing clip: 1100022039 → Label: 0
Processing clip: 1100022045 → Label: 0
Processing clip: 1100022046 → Label: 0
Processing clip: 1100022047 → Label: 1
Processing clip: 1100022048 → Label: 1
Processing clip: 1100022049 → Label: 1
Processing clip: 1100022051 → Label: 1
Processing clip: 1100022052 → Label: 1
Processing clip: 1100022053 → Label: 1
Processing clip: 1100022054 → Label: 0
Processing clip: 1100022055 → Label: 0
Processing clip: 1100022056 → Label: 0
Processing clip: 1100022057 → Label: 0
Processing clip: 1100041006 → Label: 0
Processing clip: 1100041015 → Label: 0
Processing clip: 1100041016 → Label: 0
Processing clip: 1100041017 → Label: 1
Processing clip: 1100041018 → Label: 1
Processing clip: 1100041021 → Label: 0
Processing clip: 1100041022 → Label: 1
Processing clip: 1100041023 → Label: 1
Processing clip: 1100041024 → Label: 1
Processing clip: 1100041029 → Label: 0
Processing clip: 1100041034 → Label: 0
Processing clip: 1100041044 → Label: 0
Processing clip: 1100041051 → Label: 0
Processing clip: 1100041052 → Label: 0
Processing clip: 1100042009 → Label: 1
Processing clip: 1100042010 → Label: 1
Processing clip: 1100042011 → Label: 1
Processing clip: 1100042017 → Label: 1
Processing clip: 1100042018 → Label: 0
Processing clip: 1100042019 → Label: 0
Processing clip: 1100042020 → Label: 0
Processing clip: 1100042023 → Label: 1
Processing clip: 1100042024 → Label: 1
Processing clip: 1100042025 → Label: 0
Processing clip: 1100042026 → Label: 1
Processing clip: 1100042029 → Label: 0
Processing clip: 1100042030 → Label: 0
Processing clip: 1100042031 → Label: 1
Processing clip: 1100042034 → Label: 0
Processing clip: 1100042040 → Label: 0
Processing clip: 1100042041 → Label: 0
Processing clip: 1100042058 → Label: 1
Processing clip: 1100042059 → Label: 1
Processing clip: 1100042060 → Label: 1
Processing clip: 1100051002 → Label: 0
Processing clip: 1100051004 → Label: 1
Processing clip: 1100051006 → Label: 1
Processing clip: 1100051007 → Label: 1
Processing clip: 1100051008 → Label: 1
Processing clip: 1100051009 → Label: 1
Processing clip: 1100051011 → Label: 0
Processing clip: 1100051012 → Label: 0
Processing clip: 1100051013 → Label: 1
Processing clip: 1100051014 → Label: 0
Processing clip: 1100051016 → Label: 1
Processing clip: 1100051017 → Label: 1
Processing clip: 1100051019 → Label: 1
Processing clip: 1100051020 → Label: 1
Processing clip: 1100051021 → Label: 1
Processing clip: 1100051022 → Label: 1
Processing clip: 1100051023 → Label: 0
Processing clip: 1100051024 → Label: 1
Processing clip: 1100051025 → Label: 1
Processing clip: 1100051026 → Label: 1
Processing clip: 1100051028 → Label: 1
Processing clip: 1100051029 → Label: 1
Processing clip: 1100051030 → Label: 1
Processing clip: 1100051031 → Label: 1
Processing clip: 1100051032 → Label: 0
Processing clip: 1100051033 → Label: 1
Processing clip: 1100051034 → Label: 1
Processing clip: 1100051035 → Label: 1
Processing clip: 1100051036 → Label: 1
Processing clip: 1100051037 → Label: 1
Processing clip: 1100051039 → Label: 1
Processing clip: 1100051041 → Label: 0
Processing clip: 1100051042 → Label: 1
Processing clip: 1100051044 → Label: 0
Processing clip: 1100051045 → Label: 0
Processing clip: 1100051046 → Label: 0
Processing clip: 1100051048 → Label: 1
Processing clip: 1100051049 → Label: 1
Processing clip: 1100051050 → Label: 0
Processing clip: 1100051051 → Label: 0
Processing clip: 1100051052 → Label: 1
Processing clip: 1100051053 → Label: 1
Processing clip: 1100051054 → Label: 1
Processing clip: 1100051055 → Label: 0
Processing clip: 1100051056 → Label: 1
Processing clip: 1100051057 → Label: 1
Processing clip: 1100051059 → Label: 0
Processing clip: 1100051061 → Label: 1
Processing clip: 1100051062 → Label: 1
Processing clip: 1100051064 → Label: 0
Processing clip: 1100051065 → Label: 1
Processing clip: 1100051066 → Label: 1
Processing clip: 1100051067 → Label: 1
Processing clip: 1100051068 → Label: 0
Processing clip: 1100051071 → Label: 0
Processing clip: 1100051076 → Label: 1
Processing clip: 1100051078 → Label: 0
Processing clip: 1100051079 → Label: 0
Processing clip: 1100052001 → Label: 1
Processing clip: 1100052002 → Label: 1
Processing clip: 1100052006 → Label: 1
Processing clip: 1100052007 → Label: 1
Processing clip: 1100052008 → Label: 0
Processing clip: 1100052009 → Label: 0
Processing clip: 1100052014 → Label: 1
Processing clip: 1100052023 → Label: 1
Processing clip: 1100052024 → Label: 0
Processing clip: 1100052026 → Label: 0
Processing clip: 1100052027 → Label: 1
Processing clip: 1100052028 → Label: 0
Processing clip: 1100052030 → Label: 1
Processing clip: 1100052031 → Label: 0
Processing clip: 1100052032 → Label: 1
Processing clip: 1100052033 → Label: 0
Processing clip: 1100052035 → Label: 0
Processing clip: 1100052036 → Label: 1
Processing clip: 1100052037 → Label: 1
Processing clip: 1100052038 → Label: 1
Processing clip: 1100052039 → Label: 0
Processing clip: 1100052040 → Label: 1
Processing clip: 1100052041 → Label: 1
Processing clip: 1100052047 → Label: 0
Processing clip: 1100052048 → Label: 1
Processing clip: 1100052049 → Label: 0
Processing clip: 1100052051 → Label: 1
Processing clip: 1100052055 → Label: 0
Processing clip: 1100052057 → Label: 1
Processing clip: 1100052060 → Label: 0
Processing clip: 1100052061 → Label: 1
Processing clip: 1100052062 → Label: 1
Processing clip: 1100052065 → Label: 0
Processing clip: 1100052068 → Label: 1
Processing clip: 1100052070 → Label: 1
Processing clip: 1100061009 → Label: 0
Processing clip: 1100061010 → Label: 0
Processing clip: 1100061011 → Label: 0
Processing clip: 1100061012 → Label: 0
Processing clip: 1100061013 → Label: 0
Processing clip: 1100061015 → Label: 1
Processing clip: 1100061016 → Label: 0
Processing clip: 1100061018 → Label: 1
Processing clip: 1100061019 → Label: 0
Processing clip: 1100061022 → Label: 0
Processing clip: 1100061023 → Label: 0
Processing clip: 1100061025 → Label: 1
Processing clip: 1100061027 → Label: 0
Processing clip: 1100061028 → Label: 0
Processing clip: 1100061030 → Label: 0
Processing clip: 1100061031 → Label: 0
Processing clip: 1100061032 → Label: 0
Processing clip: 1100061033 → Label: 0
Processing clip: 1100061034 → Label: 0
Processing clip: 1100061035 → Label: 0
Processing clip: 1100061036 → Label: 0
Processing clip: 1100061038 → Label: 0
Processing clip: 1100061039 → Label: 0
Processing clip: 1100061040 → Label: 0
Processing clip: 1100061042 → Label: 0
Processing clip: 1100061043 → Label: 0
Processing clip: 1100061044 → Label: 0
Processing clip: 1100061046 → Label: 0
Processing clip: 1100061047 → Label: 0
Processing clip: 1100061048 → Label: 0
Processing clip: 1100061049 → Label: 0
Processing clip: 1100061050 → Label: 1
Processing clip: 1100061051 → Label: 0
Processing clip: 1100061053 → Label: 1
Processing clip: 1100061057 → Label: 0
Processing clip: 1100061058 → Label: 0
Processing clip: 1100061061 → Label: 0
Processing clip: 1100061063 → Label: 0
Processing clip: 1100061064 → Label: 0
Processing clip: 1100061067 → Label: 0
Processing clip: 1100061068 → Label: 0
Processing clip: 1100061069 → Label: 0
Processing clip: 1100061073 → Label: 0
Processing clip: 1100061074 → Label: 0
Processing clip: 1100061077 → Label: 0
Processing clip: 1100061078 → Label: 0
Processing clip: 1100062004 → Label: 0
Processing clip: 1100062005 → Label: 1
Processing clip: 1100062007 → Label: 0
Processing clip: 1100062008 → Label: 1
Processing clip: 1100062009 → Label: 0
Processing clip: 1100062016 → Label: 0
Processing clip: 1100062017 → Label: 0
Processing clip: 1100062024 → Label: 1
Processing clip: 1100062028 → Label: 1
Processing clip: 1100062029 → Label: 1
Processing clip: 1100062036 → Label: 1
Processing clip: 1100062037 → Label: 1
Processing clip: 1100062044 → Label: 1
Processing clip: 1100062045 → Label: 1
Processing clip: 1100062046 → Label: 1
Processing clip: 1100062049 → Label: 1
Processing clip: 1100062051 → Label: 1
Processing clip: 1100062053 → Label: 0
Processing clip: 1100062054 → Label: 1
Processing clip: 1100062059 → Label: 1
Processing clip: 1100062060 → Label: 1
Processing clip: 1100062061 → Label: 0
Processing clip: 1100062062 → Label: 0
Processing clip: 1100062063 → Label: 1
Processing clip: 1100062064 → Label: 1
Processing clip: 1100062065 → Label: 0
Processing clip: 1100062066 → Label: 1
Processing clip: 1100062067 → Label: 0
Processing clip: 1100062068 → Label: 1
Processing clip: 1100062069 → Label: 0
Processing clip: 1100062070 → Label: 1
Processing clip: 1100062071 → Label: 1
Processing clip: 1100062072 → Label: 1
Processing clip: 1100071005 → Label: 1
Processing clip: 1100071006 → Label: 1
Processing clip: 1100071007 → Label: 1
Processing clip: 1100071008 → Label: 0
Processing clip: 1100071009 → Label: 1
Processing clip: 1100071010 → Label: 1
Processing clip: 1100071011 → Label: 1
Processing clip: 1100071012 → Label: 0
Processing clip: 1100071013 → Label: 0
Processing clip: 1100071014 → Label: 0
Processing clip: 1100071015 → Label: 1
Processing clip: 1100071016 → Label: 0
Processing clip: 1100071017 → Label: 1
Processing clip: 1100071018 → Label: 0
Processing clip: 1100071019 → Label: 0
Processing clip: 1100071020 → Label: 1
Processing clip: 1100071021 → Label: 0
Processing clip: 1100071022 → Label: 1
Processing clip: 1100071023 → Label: 1
Processing clip: 1100071024 → Label: 1
Processing clip: 1100071026 → Label: 1
Processing clip: 1100071027 → Label: 1
Processing clip: 1100071028 → Label: 1
Processing clip: 1100071029 → Label: 1
Processing clip: 1100071030 → Label: 0
Processing clip: 1100071031 → Label: 1
Processing clip: 1100071032 → Label: 1
Processing clip: 1100071033 → Label: 1
Processing clip: 1100071034 → Label: 0
Processing clip: 1100071035 → Label: 0
Processing clip: 1100071036 → Label: 0
Processing clip: 1100071037 → Label: 1
Processing clip: 1100071040 → Label: 0
Processing clip: 1100071041 → Label: 1
Processing clip: 1100071042 → Label: 1
Processing clip: 1100071043 → Label: 1
Processing clip: 1100071044 → Label: 1
Processing clip: 1100071045 → Label: 1
Processing clip: 1100071046 → Label: 1
Processing clip: 1100071047 → Label: 1
Processing clip: 1100071049 → Label: 0
Processing clip: 1100071050 → Label: 0
Processing clip: 1100071052 → Label: 1
Processing clip: 1100071054 → Label: 0
Processing clip: 1100071055 → Label: 1
Processing clip: 1100071056 → Label: 1
Processing clip: 1100071057 → Label: 0
Processing clip: 1100071058 → Label: 1
Processing clip: 1100071059 → Label: 1
Processing clip: 1100071060 → Label: 0
Processing clip: 1100071061 → Label: 0
Processing clip: 1100071062 → Label: 1
Processing clip: 1100071063 → Label: 0
Processing clip: 1100071064 → Label: 0
Processing clip: 1100071065 → Label: 1
Processing clip: 1100071066 → Label: 1
Processing clip: 1100071067 → Label: 0
Processing clip: 1100071069 → Label: 0
Processing clip: 1100071070 → Label: 0
Processing clip: 1100071071 → Label: 1
Processing clip: 1100071072 → Label: 1
Processing clip: 1100071073 → Label: 0
Processing clip: 1100071074 → Label: 1
Processing clip: 1100071075 → Label: 1
Processing clip: 1100071076 → Label: 1
Processing clip: 1100071077 → Label: 0
Processing clip: 1100071078 → Label: 0
Processing clip: 1100071079 → Label: 0
Processing clip: 1100071080 → Label: 0
Processing clip: 1100071081 → Label: 0
Processing clip: 1100072001 → Label: 1
Processing clip: 1100072002 → Label: 0
Processing clip: 1100072003 → Label: 0
Processing clip: 1100072004 → Label: 1
Processing clip: 1100072006 → Label: 0
Processing clip: 1100072007 → Label: 0
Processing clip: 1100072008 → Label: 1
Processing clip: 1100072009 → Label: 0
Processing clip: 1100072010 → Label: 1
Processing clip: 1100072011 → Label: 0
Processing clip: 1100072012 → Label: 0
Processing clip: 1100072013 → Label: 0
Processing clip: 1100072014 → Label: 0
Processing clip: 1100072015 → Label: 1
Processing clip: 1100072016 → Label: 1
Processing clip: 1100072021 → Label: 1
Processing clip: 1100072022 → Label: 0
Processing clip: 1100072023 → Label: 0
Processing clip: 1100072024 → Label: 0
Processing clip: 1100072027 → Label: 0
Processing clip: 1100072028 → Label: 1
Processing clip: 1100072029 → Label: 0
Processing clip: 1100072030 → Label: 1
Processing clip: 1100072031 → Label: 1
Processing clip: 1100072032 → Label: 0
Processing clip: 1100072033 → Label: 0
Processing clip: 1100072034 → Label: 1
Processing clip: 1100072036 → Label: 1
Processing clip: 1100072037 → Label: 1
Processing clip: 1100072038 → Label: 1
Processing clip: 1100072039 → Label: 1
Processing clip: 1100072040 → Label: 0
Processing clip: 1100072042 → Label: 0
Processing clip: 1100072043 → Label: 1
Processing clip: 1100072045 → Label: 1
Processing clip: 1100072047 → Label: 0
Processing clip: 1100072048 → Label: 1
Processing clip: 1100072049 → Label: 0
Processing clip: 1100072050 → Label: 1
Processing clip: 1100072051 → Label: 0
Processing clip: 1100072052 → Label: 0
Processing clip: 1100072053 → Label: 0
Processing clip: 1100072054 → Label: 0
Processing clip: 1100072056 → Label: 1
Processing clip: 1100072057 → Label: 1
Processing clip: 1100072058 → Label: 0
Processing clip: 1100072059 → Label: 1
Processing clip: 1100072060 → Label: 1
Processing clip: 1100072061 → Label: 1
Processing clip: 1100072062 → Label: 1
Processing clip: 1100072063 → Label: 0
Processing clip: 1100072065 → Label: 1
Processing clip: 1100072066 → Label: 0
Processing clip: 1100072067 → Label: 1
Processing clip: 1100072068 → Label: 0
Processing clip: 1100072069 → Label: 0
Processing clip: 1100072070 → Label: 1
Processing clip: 1100072071 → Label: 1
Processing clip: 1100072072 → Label: 0
Processing clip: 1100072073 → Label: 1
Processing clip: 1100072074 → Label: 0
Processing clip: 1100072075 → Label: 1
Processing clip: 1100072076 → Label: 1
Processing clip: 1100072077 → Label: 0
Processing clip: 1100072078 → Label: 0
Processing clip: 1100072079 → Label: 0
Processing clip: 1100072080 → Label: 1
Processing clip: 1100072081 → Label: 0
Processing clip: 1100072082 → Label: 0
Processing clip: 1100072083 → Label: 0
Processing clip: 1100072084 → Label: 0
Processing clip: 1100072085 → Label: 1
Processing clip: 1100081044 → Label: 1
Processing clip: 1100081045 → Label: 0
Processing clip: 1100081046 → Label: 1
Processing clip: 1100081047 → Label: 0
Processing clip: 1100081048 → Label: 0
Processing clip: 1100082002 → Label: 0
Processing clip: 1100082003 → Label: 0
Processing clip: 1100082018 → Label: 1
Processing clip: 1100082027 → Label: 0

In [38]:
print(f"Total Number of Frames Prepared for Training: {len(dataset)}")
print("_______________________________________________________________________________________")
print("Sample:", dataset[:5])

Total Number of Frames Prepared for Training: 72780
_______________________________________________________________________________________
Sample: [('cropped_faces\\1100011002\\face_0.jpg', 0), ('cropped_faces\\1100011002\\face_1.jpg', 0), ('cropped_faces\\1100011002\\face_2.jpg', 0), ('cropped_faces\\1100011002\\face_3.jpg', 0), ('cropped_faces\\1100011002\\face_4.jpg', 0)]

### Verifying your dataset(how many frames are 0 and how many are 1)

In [39]:
from collections import Counter

labels = [label for _,label in dataset]
print(Counter(labels)) #---> 0:Focused, 1:Mind Wandering

Counter({0: 44430, 1: 28350})

In [40]:
print("Subjects found:", os.listdir(Train_dataset_path))
print("Label dict keys (sample):", list(label_dict.keys())[:5])

Subjects found: ['110001', '110002', '110004', '110005', '110006', '110007', '110008', '110010', '110011', '110012', '110013', '110014', '110015', '110016', '110017', '110041', '111003', '181374', '200048', '200049', '200050', '200054', '202614', '205601', '210051', '210052', '210053', '210055', '210056', '210057', '210058', '210059', '210060', '210061', '226051', '240846', '248510', '290428', '303830', '310062', '310063', '310064', '310066', '310068', '310069', '310070', '310071', '310072', '310073', '310074', '310075', '310076', '310077', '310078', '310079', '310080', '310081', '310082', '310083', '334463', '337021', '342227', '350361', '400018', '401835', '411021', '411031', '414081', '459999', '522129']
Label dict keys (sample): ['1100011002', '1100011003', '1100011004', '1100011005', '1100011006']

# Step-6 : CNN + Attention-Based MIL

### dataset --> mil dataset
#### (frame, label) --> (frames_of_clip, clip_label)

In [41]:
import re
def extract_number(filename):
    return int(re.search(r'\d+',filename).group())
    
mil_dataset = []

for clip_id in os.listdir(save_root):
    clip_folder = os.path.join(save_root, clip_id)
    if not os.path.isdir(clip_folder):
        continue

    label = label_dict.get(clip_id)
    if label is None:
        continue

    #collecting all frames for this clip
    frame_paths = [
        os.path.join(clip_folder, f)
        for f in sorted(os.listdir(clip_folder), key=extract_number)
        if f.lower().endswith((".jpg", ".png", ".jpeg"))
    ]

    #skip empty clip
    if len(frame_paths) == 0:
        continue

    mil_dataset.append((frame_paths, label)) #--> takes tupple : (frames_of_clip,label)

print(f"Total Clips: {len(mil_dataset)}")
print(f"Sample bag: {mil_dataset[0][0][:6]} , Label: {mil_dataset[0][1]}")

Total Clips: 4852
Sample bag: ['cropped_faces\\1100011002\\face_0.jpg', 'cropped_faces\\1100011002\\face_1.jpg', 'cropped_faces\\1100011002\\face_2.jpg', 'cropped_faces\\1100011002\\face_3.jpg', 'cropped_faces\\1100011002\\face_4.jpg', 'cropped_faces\\1100011002\\face_5.jpg'] , Label: 0

# CNN Feature extractor

In [42]:
import torch
import torch.nn as nn
import torchvision.models as models
import torchvision.transforms as transforms
from PIL import Image

In [43]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

resnet = models.resnet18(pretrained=True)
resnet.fc = nn.Identity() # Remove classifier
resnet = resnet.to(device)
resnet.eval()

C:\Users\dell\anaconda3\envs\mtcnn_env\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\dell\anaconda3\envs\mtcnn_env\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (layer2): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (downsample): Sequential(
        (0): Conv2d(64, 128, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): BasicBlock(
      (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (layer3): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (downsample): Sequential(
        (0): Conv2d(128, 256, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): BasicBlock(
      (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (layer4): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(256, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (downsample): Sequential(
        (0): Conv2d(256, 512, kernel_size=(1, 1), stride=(2, 2), bias=False)
        (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): BasicBlock(
      (conv1): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(1, 1))
  (fc): Identity()
)

### Image Preprocessing

In [44]:
#Load & preprocess all frames

transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(), # PIL format --> PyTorch tensor
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

### Convert Frames → Feature Bag (T, 512)

In [45]:
def extract_clip_features(frame_paths):
    features = []

    with torch.no_grad():
        for path in frame_paths:
            img = Image.open(path).convert("RGB")
            img = transform(img).unsqueeze(0).to(device)  # (1,3,224,224)

            feat = resnet(img)  # (1,512)
            features.append(feat.squeeze(0))

    return torch.stack(features)

In [46]:
# Load all frames of one clip -->Model treats this as ONE training sample
frame_paths, label = mil_dataset[0]

### One-Time CNN Feature Extraction

In [47]:
os.makedirs("features", exist_ok=True)

In [48]:
import numpy as np

print(len(mil_dataset))
for clip_id, (frame_paths, label) in enumerate(mil_dataset):

    save_path = f"features/{clip_id}.npy"

    # Skip if already extracted
    if os.path.exists(save_path):
        continue
        

    bag_features = extract_clip_features(frame_paths)  # (T,512)

    np.save(save_path, bag_features.cpu().numpy())

4852

### Create Final MIL Dataset

In [49]:
final_mil_dataset = []

for clip_id, (_, label) in enumerate(mil_dataset):
    feature_path = f"features/{clip_id}.npy"

    bag = torch.tensor(np.load(feature_path))
    final_mil_dataset.append((bag, torch.tensor(label)))

## Step-7 : Attention learns which frames matter

In [50]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class attentionMIL(nn.Module):
    def __init__(self, feature_dim = 512, hidden_dim=128):
        super().__init__()
        self.attention = nn.Sequential(
            nn.Linear(feature_dim, hidden_dim),
            nn.Tanh(),
            nn.Linear(hidden_dim,1)
        )

        self.classifier = nn.Sequential(
            nn.Linear(feature_dim, 1),
            nn.Sigmoid()
        )

    def forward(self, bag): 
        scores = self.attention(bag) #(num_frames,1)
        weights = F.softmax(scores, dim=0)

        #combines all frames into one vector
        clip_feature = torch.sum(weights * bag, dim=0)

        y = self.classifier(clip_feature)         # (1)
        return y, weights

# Step-8 : Training Loop

In [51]:
model = attentionMIL().to(device)
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

In [52]:
num_epochs = 25

for epoch in range(num_epochs):
    total_loss = 0

    for bag, label in final_mil_dataset:
        bag = bag.to(device)
        label = label.float().unsqueeze(0).to(device)

        optimizer.zero_grad()

        output, attention = model(bag)
        loss = criterion(output, label)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch [{epoch+1}/{num_epochs}] Loss: {total_loss:.4f}")

Epoch [1/25] Loss: 3163.2067
Epoch [2/25] Loss: 3158.8753
Epoch [3/25] Loss: 3158.6093
Epoch [4/25] Loss: 3158.2767
Epoch [5/25] Loss: 3158.5193
Epoch [6/25] Loss: 3158.6140
Epoch [7/25] Loss: 3158.4907
Epoch [8/25] Loss: 3158.4697
Epoch [9/25] Loss: 3160.2599
Epoch [10/25] Loss: 3159.9845
Epoch [11/25] Loss: 3161.3705
Epoch [12/25] Loss: 3161.5021
Epoch [13/25] Loss: 3161.5007
Epoch [14/25] Loss: 3161.5013
Epoch [15/25] Loss: 3161.5009
Epoch [16/25] Loss: 3161.5831
Epoch [17/25] Loss: 3161.5030
Epoch [18/25] Loss: 3161.5009
Epoch [19/25] Loss: 3161.5009
Epoch [20/25] Loss: 3157.7642
Epoch [21/25] Loss: 3158.4622
Epoch [22/25] Loss: 3158.4662
Epoch [23/25] Loss: 3158.4808
Epoch [24/25] Loss: 3158.5138
Epoch [25/25] Loss: 3158.5352

In [53]:
#Saving weight
torch.save(model.state_dict(), "attention_mil.pth") #trained weights & biases

# Prediction

In [54]:
def predict_clip(frame_paths):
    model.eval()

    bag = extract_clip_features(frame_paths).to(device)

    with torch.no_grad():
        prob, attention = model(bag)

    pred = 1 if prob.item() > 0.5 else 0
    return prob.item(), pred, attention

In [55]:
test_clip_frames, true_label = mil_dataset[0]

In [56]:
prob, pred, attn = predict_clip(test_clip_frames)
print("Probability:", prob)
print("Prediction on Train video:", "Mind Wandering" if pred==1 else "Focused")

Probability: 0.3424815833568573
Prediction: Focused

# Finally : Testing

In [57]:
Test_dataset_path = "mind_w/Test"

for class_name in os.listdir(Test_dataset_path):
    class_path = os.path.join(Test_dataset_path, class_name)
    if os.path.isdir(class_path):
        print(f"class: {class_name}, video: {len(os.listdir(class_path))}")

class: 500044, video: 119
class: 500067, video: 126
class: 500095, video: 112
class: 510009, video: 84
class: 510034, video: 81
class: 510035, video: 84
class: 510036, video: 6
class: 510037, video: 31
class: 510038, video: 124
class: 510040, video: 112
class: 510042, video: 129
class: 510045, video: 88
class: 510046, video: 122
class: 510047, video: 83
class: 826412, video: 84
class: 882654, video: 91
class: 907001, video: 55
class: 928901, video: 84
class: 940328, video: 67
class: 987736, video: 98
class: 998826, video: 86

## Scanning & Collecting all video files.

In [58]:
test_root_folder = r"C:\Users\dell\mind_w\Test"

#List to store all video files
test_video_files = []
# Walk through all subfolders
for subdir,dirs,files in os.walk(test_root_folder):
    for f in files:
        if f.lower().endswith(('.avi', '.AVI', '.mov', '.mpg', '.mp4')):
            full_path = os.path.join(subdir,f)
            test_video_files.append(full_path)

print("Total Video Found: ", len(test_video_files))
# show first 10 videos as a sample
print(test_video_files[:10])

Total Video Found:  1866
['C:\\Users\\dell\\mind_w\\Test\\500044\\5000441001\\5000441001.avi', 'C:\\Users\\dell\\mind_w\\Test\\500044\\5000441002\\5000441002.avi', 'C:\\Users\\dell\\mind_w\\Test\\500044\\5000441003\\5000441003.avi', 'C:\\Users\\dell\\mind_w\\Test\\500044\\5000441005\\5000441005.avi', 'C:\\Users\\dell\\mind_w\\Test\\500044\\5000441006\\5000441006.avi', 'C:\\Users\\dell\\mind_w\\Test\\500044\\5000441007\\5000441007.avi', 'C:\\Users\\dell\\mind_w\\Test\\500044\\5000441008\\5000441008.avi', 'C:\\Users\\dell\\mind_w\\Test\\500044\\5000441009\\5000441009.avi', 'C:\\Users\\dell\\mind_w\\Test\\500044\\5000441010\\5000441010.avi', 'C:\\Users\\dell\\mind_w\\Test\\500044\\5000441012\\5000441012.avi']

### Convert .avi-->.mp4

In [58]:
import subprocess

PRINT_LIMIT = 10   # only show logs for first 10 files

for idx, file_path in enumerate(test_video_files):
    # Skip if already .mp4
    if file_path.lower().endswith('.mp4'):
        continue

    # Output path: same folder, same name with .mp4 extension
    output_path = os.path.splitext(file_path)[0] + ".mp4"

    # FFmpeg command
    command = [
        "ffmpeg",
        "-i", file_path,
        "-c:v", "libx264",
        "-preset", "fast",
        "-crf", "23",
        "-c:a", "aac",
        output_path
    ]

    subprocess.run(
        command,
        stdout=subprocess.DEVNULL,   # silence ffmpeg output
        stderr=subprocess.DEVNULL
    )
    if idx < PRINT_LIMIT:
        print(f"Converted: {file_path} → {output_path}")

Converted: C:\Users\dell\mind_w\Test\500044\5000441001\5000441001.avi → C:\Users\dell\mind_w\Test\500044\5000441001\5000441001.mp4
Converted: C:\Users\dell\mind_w\Test\500044\5000441002\5000441002.avi → C:\Users\dell\mind_w\Test\500044\5000441002\5000441002.mp4
Converted: C:\Users\dell\mind_w\Test\500044\5000441003\5000441003.avi → C:\Users\dell\mind_w\Test\500044\5000441003\5000441003.mp4
Converted: C:\Users\dell\mind_w\Test\500044\5000441005\5000441005.avi → C:\Users\dell\mind_w\Test\500044\5000441005\5000441005.mp4
Converted: C:\Users\dell\mind_w\Test\500044\5000441006\5000441006.avi → C:\Users\dell\mind_w\Test\500044\5000441006\5000441006.mp4
Converted: C:\Users\dell\mind_w\Test\500044\5000441007\5000441007.avi → C:\Users\dell\mind_w\Test\500044\5000441007\5000441007.mp4
Converted: C:\Users\dell\mind_w\Test\500044\5000441008\5000441008.avi → C:\Users\dell\mind_w\Test\500044\5000441008\5000441008.mp4
Converted: C:\Users\dell\mind_w\Test\500044\5000441009\5000441009.avi → C:\Users\dell\mind_w\Test\500044\5000441009\5000441009.mp4
Converted: C:\Users\dell\mind_w\Test\500044\5000441010\5000441010.avi → C:\Users\dell\mind_w\Test\500044\5000441010\5000441010.mp4
Converted: C:\Users\dell\mind_w\Test\500044\5000441012\5000441012.avi → C:\Users\dell\mind_w\Test\500044\5000441012\5000441012.mp4

### Frame Extraction

In [59]:
def load_video(test_video_path, num_frames=24):
    frames = []

    try:
        cap = cv2.VideoCapture(test_video_path)
        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        fps = cap.get(cv2.CAP_PROP_FPS)

        if total_frames == 0 or fps == 0:
            return None

        # sample one frame every 0.5 seconds
        step = int(fps * 0.5)

        for i in range(0, total_frames, step):
            cap.set(cv2.CAP_PROP_POS_FRAMES, i)
            ret, frame = cap.read()
            if not ret:
                continue

            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            frame = cv2.resize(frame, (224, 224))
            frames.append(frame)

            if len(frames) == num_frames:
                break

        cap.release()
        return np.array(frames)

    except Exception as e:
        print(f"Error reading {test_video_path}: {e}")
        return None

In [60]:
for root, dirs, files in os.walk(Test_dataset_path):
    for file in files:
        if file.lower().endswith(".mp4"):
            print(os.path.join(root,file))

mind_w/Test\882654\88265401100\88265401100.mp4
mind_w/Test\882654\88265401130\88265401130.mp4
mind_w/Test\882654\88265401140\88265401140.mp4
mind_w/Test\882654\88265401150\88265401150.mp4
mind_w/Test\882654\88265401160\88265401160.mp4
mind_w/Test\882654\88265401170\88265401170.mp4
mind_w/Test\882654\88265401190\88265401190.mp4
mind_w/Test\882654\8826540120\8826540120.mp4
mind_w/Test\882654\88265401200\88265401200.mp4
mind_w/Test\882654\88265401240\88265401240.mp4
mind_w/Test\882654\88265401260\88265401260.mp4
mind_w/Test\882654\88265401270\88265401270.mp4
mind_w/Test\882654\88265401280\88265401280.mp4
mind_w/Test\882654\88265401300\88265401300.mp4
mind_w/Test\882654\88265401320\88265401320.mp4
mind_w/Test\882654\88265401350\88265401350.mp4
mind_w/Test\882654\88265401360\88265401360.mp4
mind_w/Test\882654\88265401380\88265401380.mp4
mind_w/Test\882654\88265401390\88265401390.mp4
mind_w/Test\882654\88265401400\88265401400.mp4
mind_w/Test\882654\88265401410\88265401410.mp4
mind_w/Test\882654\88265401420\88265401420.mp4
mind_w/Test\882654\88265401430\88265401430.mp4
mind_w/Test\882654\88265401450\88265401450.mp4
mind_w/Test\882654\88265401470\88265401470.mp4
mind_w/Test\882654\88265401480\88265401480.mp4
mind_w/Test\882654\88265401490\88265401490.mp4
mind_w/Test\882654\8826540150\8826540150.mp4
mind_w/Test\882654\88265401520\88265401520.mp4
mind_w/Test\882654\88265401550\88265401550.mp4
mind_w/Test\882654\88265401630\88265401630.mp4
mind_w/Test\882654\88265401640\88265401640.mp4
mind_w/Test\882654\88265401660\88265401660.mp4
mind_w/Test\882654\88265401690\88265401690.mp4
mind_w/Test\882654\8826540170\8826540170.mp4
mind_w/Test\882654\88265401730\88265401730.mp4
mind_w/Test\882654\88265401740\88265401740.mp4
mind_w/Test\882654\88265401750\88265401750.mp4
mind_w/Test\882654\8826540180\8826540180.mp4
mind_w/Test\882654\88265402120\88265402120.mp4
mind_w/Test\882654\88265402150\88265402150.mp4
mind_w/Test\882654\88265402160\88265402160.mp4
mind_w/Test\882654\88265402170\88265402170.mp4
mind_w/Test\882654\88265402180\88265402180.mp4
mind_w/Test\882654\88265402190\88265402190.mp4
mind_w/Test\882654\88265402200\88265402200.mp4
mind_w/Test\882654\88265402230\88265402230.mp4
mind_w/Test\882654\88265402240\88265402240.mp4
mind_w/Test\882654\88265402270\88265402270.mp4
mind_w/Test\882654\8826540230\8826540230.mp4
mind_w/Test\882654\88265402300\88265402300.mp4
mind_w/Test\882654\88265402310\88265402310.mp4
mind_w/Test\882654\88265402320\88265402320.mp4
mind_w/Test\882654\88265402330\88265402330.mp4
mind_w/Test\882654\88265402340\88265402340.mp4
mind_w/Test\882654\88265402350\88265402350.mp4
mind_w/Test\882654\88265402370\88265402370.mp4
mind_w/Test\882654\88265402380\88265402380.mp4
mind_w/Test\882654\8826540240\8826540240.mp4
mind_w/Test\882654\88265402400\88265402400.mp4
mind_w/Test\882654\88265402420\88265402420.mp4
mind_w/Test\882654\88265402440\88265402440.mp4
mind_w/Test\882654\88265402450\88265402450.mp4
mind_w/Test\882654\88265402480\88265402480.mp4
mind_w/Test\882654\88265402490\88265402490.mp4
mind_w/Test\882654\88265402500\88265402500.mp4
mind_w/Test\882654\88265402520\88265402520.mp4
mind_w/Test\882654\88265402540\88265402540.mp4
mind_w/Test\882654\88265402570\88265402570.mp4
mind_w/Test\882654\88265402580\88265402580.mp4
mind_w/Test\882654\88265402590\88265402590.mp4
mind_w/Test\882654\8826540260\8826540260.mp4
mind_w/Test\882654\88265402600\88265402600.mp4
mind_w/Test\882654\88265402630\88265402630.mp4
mind_w/Test\882654\88265402660\88265402660.mp4
mind_w/Test\882654\88265402690\88265402690.mp4
mind_w/Test\882654\8826540270\8826540270.mp4
mind_w/Test\882654\88265402700\88265402700.mp4
mind_w/Test\882654\88265402770\88265402770.mp4
mind_w/Test\882654\88265402780\88265402780.mp4
mind_w/Test\882654\88265402790\88265402790.mp4
mind_w/Test\882654\8826540280\8826540280.mp4
mind_w/Test\882654\88265402800\88265402800.mp4
mind_w/Test\882654\88265402810\88265402810.mp4
mind_w/Test\882654\88265402820\88265402820.mp4
mind_w/Test\882654\88265402840\88265402840.mp4
mind_w/Test\882654\88265402850\88265402850.mp4
mind_w/Test\882654\88265402880\88265402880.mp4
mind_w/Test\882654\88265402890\88265402890.mp4
mind_w/Test\882654\8826540290\8826540290.mp4
mind_w/Test\882654\88265402900\88265402900.mp4
mind_w/Test\907001\907001100\907001100.mp4
mind_w/Test\907001\9070011010\9070011010.mp4
mind_w/Test\907001\9070011020\9070011020.mp4
mind_w/Test\907001\9070011060\9070011060.mp4
mind_w/Test\907001\9070011090\9070011090.mp4
mind_w/Test\907001\907001110\907001110.mp4
mind_w/Test\907001\9070011110\9070011110.mp4
mind_w/Test\907001\907001120\907001120.mp4
mind_w/Test\907001\907001150\907001150.mp4
mind_w/Test\907001\907001160\907001160.mp4
mind_w/Test\907001\907001170\907001170.mp4
mind_w/Test\907001\907001180\907001180.mp4
mind_w/Test\907001\907001210\907001210.mp4
mind_w/Test\907001\907001220\907001220.mp4
mind_w/Test\907001\907001240\907001240.mp4
mind_w/Test\907001\907001270\907001270.mp4
mind_w/Test\907001\907001280\907001280.mp4
mind_w/Test\907001\907001310\907001310.mp4
mind_w/Test\907001\907001340\907001340.mp4
mind_w/Test\907001\907001350\907001350.mp4
mind_w/Test\907001\907001360\907001360.mp4
mind_w/Test\907001\907001370\907001370.mp4
mind_w/Test\907001\907001400\907001400.mp4
mind_w/Test\907001\907001430\907001430.mp4
mind_w/Test\907001\907001450\907001450.mp4
mind_w/Test\907001\907001480\907001480.mp4
mind_w/Test\907001\907001490\907001490.mp4
mind_w/Test\907001\90700150\90700150.mp4
mind_w/Test\907001\907001500\907001500.mp4
mind_w/Test\907001\907001520\907001520.mp4
mind_w/Test\907001\907001550\907001550.mp4
mind_w/Test\907001\907001560\907001560.mp4
mind_w/Test\907001\907001570\907001570.mp4
mind_w/Test\907001\907001580\907001580.mp4
mind_w/Test\907001\90700160\90700160.mp4
mind_w/Test\907001\907001600\907001600.mp4
mind_w/Test\907001\907001620\907001620.mp4
mind_w/Test\907001\907001650\907001650.mp4
mind_w/Test\907001\907001670\907001670.mp4
mind_w/Test\907001\907001680\907001680.mp4
mind_w/Test\907001\90700170\90700170.mp4
mind_w/Test\907001\907001730\907001730.mp4
mind_w/Test\907001\907001740\907001740.mp4
mind_w/Test\907001\907001780\907001780.mp4
mind_w/Test\907001\907001790\907001790.mp4
mind_w/Test\907001\90700180\90700180.mp4
mind_w/Test\907001\907001820\907001820.mp4
mind_w/Test\907001\907001840\907001840.mp4
mind_w/Test\907001\907001850\907001850.mp4
mind_w/Test\907001\907001860\907001860.mp4
mind_w/Test\907001\90700190\90700190.mp4
mind_w/Test\907001\907001910\907001910.mp4
mind_w/Test\907001\907001940\907001940.mp4
mind_w/Test\907001\907001950\907001950.mp4
mind_w/Test\907001\907001970\907001970.mp4

In [101]:
frames = load_video("mind_w\Test\907001\907001950\907001950.mp4",24)

### Face Detection & Cropping

In [102]:
os.makedirs("detected_faces", exist_ok=True)

face_count = 0

for idx, frame in enumerate(frames):
    try:
        # Ensure correct format
        frame = frame.astype(np.uint8)

        #FACE DETECTION (PASS NUMPY IMAGE DIRECTLY)
        face = mtcnn(frame)

        if face is not None:
            # face is [3, 160, 160] tensor
            face_img = face.permute(1, 2, 0).numpy()
            face_img = (face_img * 255).astype(np.uint8)

            cv2.imwrite(
                f"detected_faces_{face_count}.jpg",
                cv2.cvtColor(face_img, cv2.COLOR_RGB2BGR)
            )

            face_count += 1

    except Exception as e:
        print(f"Skipped frame {idx}: {e}")

print("Total faces detected:", face_count)

Total faces detected: 21

### Cropping

In [103]:
def extract_clip_features_from_faces(face_images):
    """
    face_images: numpy array (T, H, W, 3)
    returns: torch tensor (T, 512)
    """
    features = []

    with torch.no_grad():
        for face in face_images:
            img = Image.fromarray(face).convert("RGB")
            img = transform(img).unsqueeze(0).to(device)

            feat = resnet(img)        # (1,512)
            features.append(feat.squeeze(0))

    return torch.stack(features)

In [104]:
test_faces = extract_faces(frames, mtcnn, min_face_size=16)

In [105]:
test_bag = extract_clip_features_from_faces(test_faces)  # (T,512)

In [106]:
label_df = pd.read_csv("Labels/TestLabels.csv")
label_df.head()

           ClipID  Boredom  Engagement  Confusion  Frustration
0  5000441001.avi        1           2          0             0
1  5000441002.avi        0           2          0             0
2  5000441003.avi        1           2          0             0
3  5000441005.avi        2           2          0             0
4  5000441006.avi        2           2          1             2

In [97]:
#remove .avi from clipID
label_df["ClipID"] = label_df["ClipID"].str.replace(".avi","",regex=False)

#remove extra spaces in column name
label_df.columns = label_df.columns.str.strip()

# Combine Rule
label_df["BinaryLabel"] = label_df.apply(
    lambda row : 1 if (row["Boredom"]+row["Confusion"]+row["Frustration"]) >= row["Engagement"]
    else 0, axis=1
)
# where 0-->Focused & 1-->Mind_Wandering

print(label_df["BinaryLabel"].value_counts())

BinaryLabel
0    1116
1     668
Name: count, dtype: int64

In [98]:
label_map = dict(
    zip(label_df["ClipID"].astype(str), label_df["BinaryLabel"])
)

print("Total labels:", len(label_map))

Total labels: 1784

### Predict using Attention-MIL

In [100]:
model.eval()

with torch.no_grad():
    prob, attn = model(test_bag.to(device))

prediction = "Mind Wandering" if prob.item() > 0.5 else "Focused"

print("Probability:", prob.item())
print("Prediction:", prediction)

Probability: 0.2826272249221802
Prediction: Focused